'use strict';
const $=id=>document.getElementById(id);
const MODULES=['M01','M02','M03','M04','M05','M06','M07','M08','M09','M10','M11','M12','M13'];
const POOL=[...(window.M14_POOL_1||[]),...(window.M14_POOL_2||[]),...(window.M14_POOL_3||[]),...(window.M14_POOL_4A||[]),...(window.M14_POOL_4B||[])], MODN=window.M14_MODULES, CAPS=window.M14_CAPSTONES;
const KSTATE='tva_m14_legal_qa_v2',KHIST='tva_m14_history_v2',KPROG='tva_m14_progress_v2',KCAP='tva_m14_capstones_v2',DASH='tvaSpecialisteTvaDashboardV1';
const CFG={
 diag:{label:'Diagnostic · 26Q',mins:45,pattern:['F','M'],desc:'2 questions par module. Rapide, équilibré, utile avant révision.'},
 standard:{label:'Standard · 39Q',mins:60,pattern:['F','M','D'],desc:'3 questions par module: fondamentaux, pratique et difficulté.'},
 senior:{label:'Senior · 39Q',mins:70,pattern:['M','D','D'],desc:'3 questions par module, poids fort sur raisonnement difficile.'},
 final:{label:'Final Pro · 52Q',mins:90,pattern:['F','M','M','D'],desc:'4 questions par module. Seul ce mode peut valider le gate examen.'},
 random:{label:'Random · 30Q',mins:60,pattern:null,desc:'Tirage libre du pool pour entraînement; couverture non garantie.'}
};
function jload(k,d){try{const x=localStorage.getItem(k);return x?JSON.parse(x):d}catch(e){return d}}
function jsave(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
let state=jload(KSTATE,{bestFinal:0,finalPassed:false,courseDone:false});
let capstate=jload(KCAP,{});
let quiz={active:false,set:null,questions:[],answers:{},marks:{},idx:0,endAt:0,startAt:0,timer:null};
let last=null;
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function prep(q){const order=shuffle(q.options.map((_,i)=>i));const c=Object.assign({},q);c.options=order.map(i=>q.options[i]);c.correct=order.indexOf(q.correct);return c}
function pickOne(mod,diff,used){let c=POOL.filter(q=>q.module===mod&&q.difficulty===diff&&!used.has(q.id));if(!c.length)c=POOL.filter(q=>q.module===mod&&!used.has(q.id));if(!c.length)throw new Error('Pool insuffisant '+mod);const x=shuffle(c)[0];used.add(x.id);return x}
function sample(set){if(set==='random')return shuffle(POOL).slice(0,30).map(prep);const used=new Set(),out=[];MODULES.forEach(m=>CFG[set].pattern.forEach(d=>out.push(pickOne(m,d,used))));return shuffle(out).map(prep)}
function go(s){document.querySelectorAll('.sec').forEach(x=>x.classList.remove('active'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$('sec-'+s).classList.add('active');const b=document.querySelector('[data-s="'+s+'"]');if(b)b.classList.add('active');const m=document.querySelector('.mobile');if(m)m.value=s;if(s==='results')renderResults();if(s==='history')renderHistory();if(s==='validation')renderValidation();scrollTo(0,0)}
function renderModes(){$('modeCards').innerHTML=Object.keys(CFG).map(k=>'<div class="mode"><h3>'+CFG[k].label+'</h3><p>'+CFG[k].desc+'</p><div class="meta">'+CFG[k].mins+' min · seuil entraînement 75%'+(k==='final'?' · module floor 50%':'')+'</div><button class="btn '+(k==='final'?'navy':'primary')+'" onclick="startExam(\''+k+'\')">▶ Démarrer</button></div>').join('')}
function startExam(set){if(quiz.active&&!confirm('Abandonner la tentative en cours ?'))return;if(quiz.timer)clearInterval(quiz.timer);const qq=sample(set);quiz={active:true,set:set,questions:qq,answers:{},marks:{},idx:0,startAt:Date.now(),endAt:Date.now()+CFG[set].mins*60000,timer:null};$('runtime').classList.add('active');$('examName').textContent=CFG[set].label;$('totalCount').textContent=qq.length;renderGrid();renderQ();startTimer();saveProgress();window.scrollTo(0,$('runtime').offsetTop-70)}
function startTimer(){if(quiz.timer)clearInterval(quiz.timer);const tick=()=>{const s=Math.max(0,Math.ceil((quiz.endAt-Date.now())/1000));$('timer').textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');$('timer').classList.toggle('urgent',s<300);if(s<=0){clearInterval(quiz.timer);quiz.timer=null;finishExam('timeout')}};tick();quiz.timer=setInterval(tick,1000)}
function renderGrid(){$('qgrid').innerHTML=quiz.questions.map((q,i)=>'<button class="qg" data-i="'+i+'" onclick="jump('+i+')">'+(i+1)+'</button>').join('');updateGrid()}
function updateGrid(){document.querySelectorAll('.qg').forEach((b,i)=>{const q=quiz.questions[i];b.classList.toggle('current',i===quiz.idx);b.classList.toggle('answered',quiz.answers[q.id]!==undefined);b.classList.toggle('marked',!!quiz.marks[q.id])});$('answeredCount').textContent=Object.keys(quiz.answers).length;$('markedCount').textContent=Object.values(quiz.marks).filter(Boolean).length}
function renderQ(){const q=quiz.questions[quiz.idx];$('qmod').textContent=q.module;$('qdiff').textContent=q.difficulty;$('qcomp').textContent=q.competence;$('qtext').textContent=q.question;$('qopts').innerHTML='';q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='opt'+(quiz.answers[q.id]===i?' selected':'');b.textContent=String.fromCharCode(65+i)+') '+o;b.onclick=()=>choose(i);$('qopts').appendChild(b)});$('markBtn').textContent=quiz.marks[q.id]?'🚩 marquée':'☆ à revoir';$('prevBtn').disabled=quiz.idx===0;$('nextBtn').disabled=quiz.idx===quiz.questions.length-1;updateGrid()}
function choose(i){const q=quiz.questions[quiz.idx];quiz.answers[q.id]=i;renderQ();saveProgress()}
function moveQ(d){const n=quiz.idx+d;if(n>=0&&n<quiz.questions.length){quiz.idx=n;renderQ();saveProgress()}}
function jump(i){quiz.idx=i;renderQ();saveProgress()}
function toggleMark(){const q=quiz.questions[quiz.idx];quiz.marks[q.id]=!quiz.marks[q.id];renderQ();saveProgress()}
function saveProgress(){if(!quiz.active){jsave(KPROG,null);return}jsave(KPROG,{active:true,set:quiz.set,questions:quiz.questions,answers:quiz.answers,marks:quiz.marks,idx:quiz.idx,startAt:quiz.startAt,endAt:quiz.endAt})}
function restoreProgress(){const x=jload(KPROG,null);if(!x||!x.active||!Array.isArray(x.questions))return false;quiz={active:true,set:x.set,questions:x.questions,answers:x.answers||{},marks:x.marks||{},idx:x.idx||0,startAt:x.startAt,endAt:x.endAt,timer:null};if(Date.now()>=quiz.endAt){finishExam('timeout');return true}go('modes');$('runtime').classList.add('active');$('examName').textContent=CFG[quiz.set].label;$('totalCount').textContent=quiz.questions.length;renderGrid();renderQ();startTimer();return true}
function submitExam(){if(!quiz.active)return;const n=Object.keys(quiz.answers).length;if(!confirm('Terminer l’examen ? '+n+'/'+quiz.questions.length+' question(s) répondue(s). Les vides valent 0 point.'))return;finishExam('submit')}
function finishExam(reason){if(quiz.timer){clearInterval(quiz.timer);quiz.timer=null}if(!quiz.questions.length)return;quiz.active=false;const byModule={},wrong=[];let correct=0;MODULES.forEach(m=>byModule[m]={c:0,t:0});quiz.questions.forEach(q=>{byModule[q.module].t++;const a=quiz.answers[q.id];if(a===q.correct){correct++;byModule[q.module].c++}else wrong.push(q.id)});const total=quiz.questions.length,pct=Math.round(correct/total*100);const moduleFloor=MODULES.every(m=>!byModule[m].t||Math.round(byModule[m].c/byModule[m].t*100)>=50);const passed=quiz.set==='final'?pct>=75&&moduleFloor:pct>=75;const att={ts:Date.now(),set:quiz.set,label:CFG[quiz.set].label,correct,total,pct,passed,moduleFloor,byModule,wrongIds:wrong,answers:Object.assign({},quiz.answers),questions:quiz.questions,timeSpent:Math.round((Date.now()-quiz.startAt)/1000),reason};let h=jload(KHIST,[]);h.unshift(att);h=h.slice(0,40);jsave(KHIST,h);last=att;if(quiz.set==='final'){state.bestFinal=Math.max(state.bestFinal||0,pct);if(passed)state.finalPassed=true;jsave(KSTATE,state)}jsave(KPROG,null);$('runtime').classList.remove('active');quiz={active:false,set:null,questions:[],answers:{},marks:{},idx:0,endAt:0,startAt:0,timer:null};refresh();go('results')}
function getLast(){if(last)return last;const h=jload(KHIST,[]);return h[0]||null}
function renderResults(){const a=getLast();$('resultsEmpty').style.display=a?'none':'block';$('resultsContent').style.display=a?'block':'none';if(!a)return;$('resultScore').textContent=a.pct+'%';$('resultTitle').textContent=a.passed?'✓ Mode réussi':'✗ Seuil non atteint';$('resultTitle').className=a.passed?'statusPass':'statusFail';$('resultDetail').textContent=a.set==='final'?(a.passed?'Final Pro validé: global ≥75% et aucun module sous 50%.':'Final Pro non validé: il faut ≥75% global ET ≥50% dans chaque module.'):(a.passed?'Seuil d’entraînement ≥75% atteint.':'Revoir les thèmes faibles avant une nouvelle tentative.');$('moduleBreakdown').innerHTML='';MODULES.forEach(m=>{const d=a.byModule[m];if(!d||!d.t)return;const p=Math.round(d.c/d.t*100),row=document.createElement('div');row.className='breakrow';row.innerHTML='<b>'+m+'</b><div><span class="note">'+MODN[m]+'</span><div class="meter"><i style="width:'+p+'%;background:'+(p>=75?'var(--gr)':p>=50?'var(--a)':'var(--r)')+'"></i></div></div><span>'+d.c+'/'+d.t+' · '+p+'%</span>';$('moduleBreakdown').appendChild(row)});const weak=MODULES.filter(m=>a.byModule[m]&&a.byModule[m].t&&Math.round(a.byModule[m].c/a.byModule[m].t*100)<75);$('remediation').innerHTML=weak.length?'<ol>'+weak.map(m=>'<li><b>'+m+'</b> — '+MODN[m]+'</li>').join('')+'</ol>':'<div class="success card">Aucun module testé sous 75 %.</div>';const map={};a.questions.forEach(q=>map[q.id]=q);$('reviewList').innerHTML=a.wrongIds.length?'': '<div class="success card">Aucune erreur.</div>';a.wrongIds.forEach(id=>{const q=map[id],ua=a.answers[id],div=document.createElement('div');div.className='review';div.innerHTML='<b>'+q.module+' · '+q.competence+'</b><p>'+q.question+'</p><p class="correct">✓ '+q.options[q.correct]+'</p>'+(ua===undefined?'<p class="wrong">Non répondue</p>':'<p class="wrong">Votre choix: '+q.options[ua]+'</p>')+'<p>'+q.explanation+'</p><p class="note">Source: '+q.source+'</p>';$('reviewList').appendChild(div)})}
function renderHistory(){const h=jload(KHIST,[]);$('historyList').innerHTML=h.length?'':'<div class="card">Aucune tentative.</div>';h.forEach(a=>{const d=new Date(a.ts),x=document.createElement('div');x.className='hist';x.innerHTML='<div><b>'+a.label+'</b><br><span class="note">'+d.toLocaleString('fr-CH')+' · '+a.correct+'/'+a.total+'</span></div><span class="pill '+(a.passed?'pass':'fail')+'">'+a.pct+'%</span>';$('historyList').appendChild(x)})}
function renderCaps(){const cs=capstate;$('capstoneList').innerHTML='';CAPS.forEach(c=>{const v=cs[c.id]||{draft:'',model:false,done:false};const el=document.createElement('div');el.className='cap'+(v.done?' done':'');el.id='cap-'+c.id;el.innerHTML='<h3>'+c.title+'</h3><div class="brief">'+c.brief+'</div><ol>'+c.tasks.map(t=>'<li>'+t+'</li>').join('')+'</ol><textarea id="draft-'+c.id+'" placeholder="Rédigez votre analyse avant d’ouvrir le modèle…"></textarea><div class="capactions"><button id="show-'+c.id+'" class="btn primary" onclick="showModel(\''+c.id+'\')">Afficher le modèle</button><button id="done-'+c.id+'" class="btn gold" onclick="markCap(\''+c.id+'\')">Marquer comme travaillé</button></div><div id="model-'+c.id+'" class="model"><b>Modèle de contrôle</b><p>'+c.model+'</p></div><p id="hint-'+c.id+'" class="note"></p>';$('capstoneList').appendChild(el);$('draft-'+c.id).value=v.draft||'';$('draft-'+c.id).oninput=e=>saveDraft(c.id,e.target.value);syncCap(c.id)})}
function saveDraft(id,val){if(!capstate[id])capstate[id]={draft:'',model:false,done:false};capstate[id].draft=val;jsave(KCAP,capstate);syncCap(id)}
function capWords(s){return ((s||'').trim().match(/\S+/g)||[]).length}
function capReady(s){const x=(s||'').trim();return x.length>=500&&capWords(x)>=80}
function syncCap(id){const v=capstate[id]||{draft:'',model:false,done:false},txt=(v.draft||'').trim(),len=txt.length,w=capWords(txt),ok=capReady(txt);$('show-'+id).disabled=!ok&&!v.model;$('done-'+id).disabled=!v.model;$('model-'+id).classList.toggle('show',!!v.model);$('hint-'+id).textContent=v.done?'Dossier enregistré comme travaillé.':v.model?'Modèle ouvert. Comparez votre raisonnement avec la correction.':ok?'Vous pouvez maintenant comparer avec le modèle.':'Réponse attendue avant le modèle : au moins 80 mots et 500 caractères. Actuellement '+w+' mots · '+len+' caractères.';const el=$('cap-'+id);if(el)el.classList.toggle('done',!!v.done)}
function showModel(id){if(!capstate[id])return;if(!capReady(capstate[id].draft||'')&&!capstate[id].model)return;capstate[id].model=true;jsave(KCAP,capstate);syncCap(id)}
function markCap(id){if(!capstate[id]||!capstate[id].model)return;capstate[id].done=true;jsave(KCAP,capstate);syncCap(id);refresh();renderValidation()}
function capsDone(){return CAPS.filter(c=>capstate[c.id]&&capstate[c.id].done).length}
function renderValidation(){const n=capsDone();$('gateExam').className='gate '+(state.finalPassed?'ok':'no');$('gateCaps').className='gate '+(n===4?'ok':'no');$('gateExamText').textContent=state.finalPassed?'Validé. Meilleur Final Pro: '+state.bestFinal+' %.':'À faire: réussir Final Pro avec ≥75 % global et ≥50 % dans chaque module.';$('gateCapsText').textContent=n+'/4 dossiers travaillés.';const ok=state.finalPassed&&n===4;$('finishBtn').disabled=!ok;$('finishTitle').textContent=state.courseDone?'Parcours déjà validé':ok?'Les deux gates sont ouverts':'Parcours non encore validé';$('finishText').textContent=state.courseDone?'M14 est enregistré comme terminé sur ce navigateur.':ok?'Vous pouvez enregistrer M14 comme terminé.':'Complétez les conditions ci-dessus.'}
function finishCourse(){if(!(state.finalPassed&&capsDone()===4))return;state.courseDone=true;jsave(KSTATE,state);try{let d=jload(DASH,{});d.M14='done';jsave(DASH,d)}catch(e){}refresh();renderValidation();$('finishText').textContent='Parcours terminé — évaluation pédagogique indépendante, pas certification officielle.'}
function refresh(){const n=capsDone(),ok1=state.finalPassed?1:0,p=Math.round((ok1+n/4)/2*100);$('coursePct').textContent=p+'%';$('courseFill').style.width=p+'%';$('bestFinal').textContent=state.bestFinal?state.bestFinal+'%':'—';$('capCount').textContent=n+'/4';document.querySelector('[data-s="capstones"]').classList.toggle('done',n===4);document.querySelector('[data-s="validation"]').classList.toggle('done',state.courseDone);$('poolCount').textContent=POOL.length+' QCM'}
function integrity(){const ids=new Set(POOL.map(q=>q.id));const counts={};MODULES.forEach(m=>counts[m]=POOL.filter(q=>q.module===m).length);const bad=POOL.filter(q=>!Array.isArray(q.options)||q.options.length!==4||q.correct<0||q.correct>3);if(POOL.length!==130||ids.size!==130||Object.values(counts).some(x=>x!==10)||bad.length)console.error('[M14] Integrity fail',POOL.length,ids.size,counts,bad);else console.log('[M14] Integrity OK: 130 QCM, 10/module')}
renderModes();renderCaps();integrity();refresh();renderValidation();renderResults();
const saved=jload(KPROG,null);if(saved&&saved.active){if(confirm('Une tentative interrompue a été détectée. La reprendre ?'))restoreProgress();else jsave(KPROG,null)}
