'use strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root=process.cwd(),die=m=>{console.error('FAIL:',m);process.exitCode=1},ok=m=>console.log('OK:',m),exists=p=>fs.existsSync(path.join(root,p)),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const modules=[['M01','m01-introduction-tva-suisse.html'],['M02','m02-qualification-operations.html'],['M03','m03-decomptes-methodes-tva.html'],['M04','m04-tva-comptabilite-suisse.html'],['M05','m05-deduction-impot-prealable-dip.html'],['M06','m06-territorialite-tva-internationale.html'],['M07','m07-holdings-groupes-tva.html'],['M08','m08-immobilier-construction-tva.html'],['M09','m09-secteurs-sensibles-tva.html'],['M10','m10-digital-plateformes-ecommerce.html'],['M11','m11-controle-afc-tva.html'],['M12','m12-jurisprudence-lab-tva.html'],['M13','m13-communication-fiscale-cabinet.html'],['M14','m14-examen-blanc-synthese-finale.html']];
const bases={M01:'m01-introduction-tva-suisse-base.html',M02:'m02-qualification-operations-base.html',M03:'m03-decomptes-methodes-tva-base.html',M04:'m04-tva-comptabilite-suisse-base.html',M05:'m05-deduction-impot-prealable-dip-base.html',M06:'m06-territorialite-tva-internationale-base.html',M07:'m07-holdings-groupes-tva-base.html',M08:'m08-immobilier-construction-tva-base.html'};
const assets=['index.html','manifest.json','legal-qa-checklist.html','course-legacy-gate.js','m12-jurisprudence-bank.js','m12-jurisprudence-data.js','m13-communication-data.js','m14-style.css','m14-engine.js','m14-caps.js','m14-q1.js','m14-q2.js','m14-q3.js','m14-q4a.js','m14-q4b.js'];
for(const [,f] of modules)if(!exists(f))die('missing '+f);for(const f of Object.values(bases))if(!exists(f))die('missing '+f);for(const f of assets)if(!exists(f))die('missing '+f);if(!process.exitCode)ok('required course files exist');
const manifest=JSON.parse(read('manifest.json'));if(manifest.module_count!==14||manifest.modules?.length!==14)die('manifest must contain 14 modules');else{const actual=manifest.modules.map(x=>x.file);for(const [,f] of modules)if(!actual.includes(f))die('manifest missing '+f);ok('manifest maps all 14 public modules')}
const htmlFiles=fs.readdirSync(root).filter(f=>f.endsWith('.html')),localRefs=[];for(const file of htmlFiles){const src=read(file);if(!/<meta[^>]+charset/i.test(src))die(file+' missing charset');if(!/<meta[^>]+name=["']viewport["']/i.test(src))die(file+' missing viewport');if(!/<title>[\s\S]*?<\/title>/i.test(src))die(file+' missing title');const clean=src.replace(/<script\b[\s\S]*?<\/script>/gi,'').replace(/<style\b[\s\S]*?<\/style>/gi,'');const ids=[...clean.matchAll(/\bid\s*=\s*["']([^"']+)["']/gi)].map(m=>m[1]),dup=[...new Set(ids.filter((v,i,a)=>a.indexOf(v)!==i))];if(dup.length)die(file+' duplicate DOM id(s): '+dup.join(', '));for(const m of src.matchAll(/\b(?:href|src)\s*=\s*["']([^"']+)["']/gi)){let ref=m[1].trim();if(!ref||ref.startsWith('#')||/^(?:https?:|mailto:|tel:|javascript:|data:|blob:)/i.test(ref))continue;ref=ref.split('#')[0].split('?')[0];if(!ref||ref.includes('{{')||ref.includes('${'))continue;localRefs.push([file,ref,path.normalize(path.join(path.dirname(file),ref))])}}
for(const [file,ref,target] of localRefs)if(!exists(target))die(`${file}: broken local ref ${ref} -> ${target}`);if(!process.exitCode)ok('static local href/src targets resolve');
const gate=read('course-legacy-gate.js');try{new Function(gate);ok('legacy gate JavaScript parses')}catch(e){die('course-legacy-gate.js syntax: '+e.message)}for(let i=1;i<=8;i++){const mid='M'+String(i).padStart(2,'0'),file=modules[i-1][1],src=read(file);if(!src.includes('COURSE_GATE_CONFIG')||!src.includes('course-legacy-gate.js')||!src.includes(bases[mid]))die(mid+' public wrapper contract broken')}if(!gate.includes("cfg.module==='M01'")||!gate.includes("cfg.module==='M03'")||!gate.includes("cfg.module==='M08'"))die('legal compatibility patches missing from legacy gate');else ok('M01–M08 wrappers share hardened gate/legal patches');
const idx=read('index.html');if(/markDone\s*\(/.test(idx)||/<button[^>]+(?:markDone|Marquer terminé)/i.test(idx))die('dashboard exposes manual completion');const modsBlock=idx.match(/const MODS\s*=\s*\[([\s\S]*?)\];/),dashCount=modsBlock?((modsBlock[1].match(/\['M\d{2}'/g)||[]).length):0;if(dashCount!==14)die('dashboard MODS must define 14 module cards, got '+dashCount);else ok('dashboard defines 14 generated cards and no manual completion bypass');
for(const [m,f] of [['M09','m09-secteurs-sensibles-tva.html'],['M10','m10-digital-plateformes-ecommerce.html'],['M11','m11-controle-afc-tva.html'],['M12','m12-jurisprudence-lab-tva.html'],['M13','m13-communication-fiscale-cabinet.html']]){const s=read(f);if(!s.includes('finishModule')||!s.includes('quizScore')||!s.includes('>=75')||!s.includes(`${m}='done'`))die(m+' completion gate contract incomplete')}if(!process.exitCode)ok('M09–M13 completion gate contracts present');
const engine=read('m14-engine.js');for(const n of ["quiz.set==='final'?pct>=75&&moduleFloor:pct>=75","state.finalPassed&&capsDone()===4","d.M14='done'"])if(!engine.includes(n))die('M14 engine missing gate invariant: '+n);if(!process.exitCode)ok('M14 final/module-floor/capstone gate present');
const sandbox={window:{},console};vm.createContext(sandbox);for(const f of ['m14-q1.js','m14-q2.js','m14-q3.js','m14-q4a.js','m14-q4b.js','m14-caps.js'])try{vm.runInContext(read(f),sandbox,{filename:f})}catch(e){die(f+' execution/syntax: '+e.message)}const pools=['M14_POOL_1','M14_POOL_2','M14_POOL_3','M14_POOL_4A','M14_POOL_4B'].flatMap(k=>sandbox.window[k]||[]);if(pools.length!==130)die('M14 pool must contain 130 questions, got '+pools.length);const ids=new Set(),texts=new Set(),counts={};for(const q of pools){if(ids.has(q.id))die('duplicate M14 id '+q.id);ids.add(q.id);if(texts.has(q.question))die('duplicate M14 question '+q.question);texts.add(q.question);if(!Array.isArray(q.options)||q.options.length!==4)die('M14 '+q.id+' not 4 options');if(!Number.isInteger(q.correct)||q.correct<0||q.correct>3)die('M14 '+q.id+' bad correct index');counts[q.module]=(counts[q.module]||0)+1}for(let i=1;i<=13;i++){const m='M'+String(i).padStart(2,'0');if(counts[m]!==10)die(`${m} must have 10 M14 questions, got ${counts[m]||0}`)}if((sandbox.window.M14_CAPSTONES||[]).length!==4)die('M14 must contain 4 capstones');if(!process.exitCode)ok('M14: 130 unique QCM, 10/module, 4 options, 4 capstones');
for(const [f,needles] of [['m09-secteurs-sensibles-tva.html',['8,1','2,6','3,8','art. 11','art. 22']],['m10-digital-plateformes-ecommerce.html',['art. 20a','CHF 5','100k']],['m11-controle-afc-tva.html',['360 jours','4,0%','art. 82','art. 83']],['m14-q1.js',["5'005'000","5'024'000","108'000"]]]){const s=read(f);for(const n of needles)if(!s.includes(n))die(`${f} missing current-law sentinel ${n}`)}if(!process.exitCode)ok('current-law sentinel checks present');if(process.exitCode)process.exit(process.exitCode);console.log('\nCOURSE STATIC QA: PASS');
