from pathlib import Path
import re, json

p=Path('m07-holdings-groupes-tva.html')
t=p.read_text(encoding='utf-8')
changes=[]

def rep(old,new,label,required=False):
    global t
    n=t.count(old)
    if not n:
        print('WARN missing',label)
        if required: raise SystemExit('missing '+label)
        return
    t=t.replace(old,new)
    changes.append((label,n))

def sub(pattern,repl,label,count=1,required=True):
    global t
    t2,n=re.subn(pattern,repl,t,count=count,flags=re.S)
    if not n:
        print('WARN regex missing',label)
        if required: raise SystemExit('missing regex '+label)
        return
    t=t2; changes.append((label,n))

# ------------------------------------------------------------------
# Branding / semantic structure / author
# ------------------------------------------------------------------
rep('Formation de spécialiste TVA suisse · M07 v4.3','Formation de spécialiste TVA suisse · M07 v5.0','footer version',True)
rep('v4.3 — final 10/10 holdings &amp; groupes','v5.0 — Holdings, participations &amp; groupes TVA','top version',True)
rep('← Dashboard','← Retour au cours','dashboard wording',True)
rep('<div class="sb-foot"><a href="index.html" style="display:block;color:var(--gold);text-decoration:none;text-align:center;font-size:11px;font-weight:600;margin-bottom:7px">← Retour au cours</a>\n<div style="font-size:11px;color:rgba(255,255,255,.35);text-align:center">Formation de spécialiste TVA suisse · M07 v5.0</div>\n</div>',
'''<div class="sb-foot"><a href="index.html" style="display:block;color:var(--gold);text-decoration:none;text-align:center;font-size:11px;font-weight:600;margin-bottom:7px">← Retour au cours</a>
<div style="font-size:11px;color:rgba(255,255,255,.35);text-align:center">Formation de spécialiste TVA suisse · M07 v5.0</div>
<div style="font-size:10px;line-height:1.5;color:rgba(255,255,255,.35);text-align:center;margin-top:8px">Conception : <a href="https://www.linkedin.com/in/mariia-lobur/" target="_blank" rel="noopener noreferrer" style="color:var(--gold)">Mariia Lobur</a> · <a href="https://github.com/mariialobur" target="_blank" rel="noopener noreferrer" style="color:var(--gold)">GitHub</a></div>
</div>''','author sidebar',True)
rep('<button class="sb-item active" data-sec="theory" onclick="NAV.go(\'theory\')"><div class="sb-dot"></div>Théorie Holdings<span class="sb-chip">12 blocs</span></button>',
    '<button class="sb-item active" data-sec="theory" onclick="NAV.go(\'theory\')"><div class="sb-dot"></div>Théorie Holdings<span class="sb-chip">12 blocs</span></button>','theory chip')

# ------------------------------------------------------------------
# SECTION A — full professional rewrite
# ------------------------------------------------------------------
theory='''<div class="section active" id="sec-theory">
<div class="hero">
<div class="hero-eye">Section A · Théorie professionnelle</div>
<h1 class="hero-h">Holdings, participations &amp; groupes TVA</h1>
<div class="hero-p">M07 relie les participations qualifiées, les dividendes, les opérations financières, les management fees, la déduction de l’impôt préalable, l’imposition de groupe et les restructurations. L’objectif n’est pas de mémoriser un « prorata holding », mais de construire un dossier défendable flux par flux.</div>
<div class="hero-chips"><span class="chip">📖 12 blocs</span><span class="chip">⚖️ LTVA 2025+</span><span class="chip">🏛 Pratique AFC</span><span class="chip">💼 Dossier fiduciaire</span><span class="chip">🕐 ~2h</span></div>
</div>
<div class="box gold"><div class="box-icon">🎯</div><div class="box-body"><div class="box-title">Objectifs professionnels de M07</div>À la fin du module, vous devez pouvoir : <strong>qualifier une participation au sens de l’art. 29, distinguer dividende / finance exclue / prestation imposable, déterminer l’assujettissement, affecter le DIP sans prorata mécanique, documenter un management fee entre proches, tester un groupe TVA, appliquer l’art. 38 et sécuriser un contrôle AFC.</strong></div></div>

<div class="block">
<div class="block-h"><span class="bnum">1</span><h3>Participation qualifiée : une activité entrepreneuriale en TVA</h3></div>
<p class="prose">L’acquisition, la détention et l’aliénation de participations visées à l’art. 29 al. 2 et 3 constituent une <strong>activité entrepreneuriale</strong> (art. 10 al. 1ter). Une participation est notamment réputée telle dès <strong>10% du capital</strong> lorsqu’elle est détenue à titre de placement durable et permet une influence déterminante.</p>
<div class="three-grid"><div class="type-card pure"><div class="type-title">Holding de participations</div><div class="type-item">Participations qualifiées, dividendes, éventuellement opérations financières.</div><div class="type-item"><strong>Assujettissement obligatoire :</strong> vérifier le CA mondial provenant de prestations non exclues.</div><div class="type-item"><strong>Volontaire :</strong> possible en principe pour une activité entrepreneuriale si les conditions de l’art. 11 sont réunies.</div></div><div class="type-card mixte"><div class="type-title">Holding avec services</div><div class="type-item">Participations + management / IT / RH / finance, etc.</div><div class="type-item"><strong>Seuil :</strong> CHF 100’000 de CA mondial déterminant provenant de prestations non exclues.</div><div class="type-item"><strong>DIP :</strong> art. 29–30, affectation réelle.</div></div><div class="type-card oper"><div class="type-title">Holding opérationnelle</div><div class="type-item">Participations + activité commerciale propre.</div><div class="type-item"><strong>TVA :</strong> qualifier chaque prestation ; des exclusions peuvent subsister.</div><div class="type-item"><strong>DIP :</strong> selon l’utilisation donnant ou non droit à déduction.</div></div></div>
<div class="box danger"><div class="box-icon">⛔</div><div class="box-body"><div class="box-title">Phrase interdite</div>« Holding pure = non-entreprise TVA = jamais de DIP ». Depuis la règle expresse de l’art. 10 al. 1ter, ce raccourci est juridiquement faux pour les participations qualifiées.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">2</span><h3>Cartographier les flux avant de calculer</h3></div>
<table class="comp-table"><thead><tr><th>Flux</th><th>Qualification TVA suisse</th><th>Réflexe DIP / preuve</th></tr></thead><tbody>
<tr><td>Dividende</td><td>Ne constitue pas une contre-prestation — art. 18 al. 2 let. f</td><td>Art. 33 al. 1 : pas de réduction du DIP du seul fait du dividende</td></tr>
<tr><td>Intérêt d’un prêt</td><td>Opération de crédit/finance généralement exclue — art. 21 al. 2 ch. 19</td><td>Affecter les coûts financiers ; ne pas assimiler au dividende</td></tr>
<tr><td>Cession de participation</td><td>Opération sur titres, avec régime spécial de DIP pour participations — art. 29 al. 2–4</td><td>SPA, mandat M&amp;A, allocation des coûts</td></tr>
<tr><td>Management / IT / RH</td><td>Prestation imposable si échange de prestations réel et lieu en Suisse</td><td>Contrat, livrables, bénéficiaire, prix de pleine concurrence</td></tr>
<tr><td>Refacturation sans marge</td><td>La marge zéro ne supprime pas une prestation</td><td>Qualifier la nature et le bénéficiaire</td></tr>
<tr><td>Flux au sein d’un groupe TVA</td><td>Interne au sujet fiscal unique</td><td>Pas de TVA interne ; suivi analytique requis</td></tr>
</tbody></table>
<div class="box info"><div class="box-icon">🧭</div><div class="box-body"><div class="box-title">Ordre de travail</div><strong>Flux → existence d’une prestation → lieu → exclusion/exonération → valeur → décompte → DIP → preuve.</strong> Le ratio de recettes vient, au mieux, à la fin comme clé de correction de certains coûts mixtes.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">3</span><h3>Dividendes : art. 18 et art. 33 doivent être lus ensemble</h3></div>
<p class="prose">Le dividende ne rémunère pas une prestation TVA. Il fait partie des éléments ne constituant pas une contre-prestation. Surtout, l’art. 33 al. 1 prévoit que les éléments visés à l’art. 18 al. 2 let. d à l — dont les dividendes — <strong>n’influencent en principe pas le montant de la déduction de l’impôt préalable</strong>.</p>
<div class="box danger"><div class="box-icon">⚠️</div><div class="box-body"><div class="box-title">Pas de « dividendes au dénominateur » automatique</div>Un calcul « management fees / (management fees + dividendes) » qui réduit mécaniquement le DIP uniquement parce qu’un dividende a été reçu contredit le réflexe art. 33 al. 1. Il faut d’abord identifier ce que les coûts servent réellement.</div></div>
<div class="box info"><div class="box-icon">↔️</div><div class="box-body"><div class="box-title">À distinguer des subventions</div>Les subventions et contributions analogues de l’art. 18 al. 2 let. a–c peuvent entraîner une réduction proportionnelle du DIP selon l’art. 33 al. 2. Dividende et subvention ne suivent donc pas la même logique.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">4</span><h3>Participations &amp; frais M&amp;A — art. 29 al. 2–4</h3></div>
<p class="prose">L’art. 29 al. 2 déroge à l’exclusion ordinaire du DIP pour certaines opérations : l’acquisition, la détention et l’aliénation de participations qualifiées ainsi que certaines restructurations donnent droit à déduction <strong>dans le cadre de l’activité entrepreneuriale donnant droit au DIP</strong>. L’al. 4 permet aux sociétés holding de tenir compte de l’activité entrepreneuriale donnant droit au DIP des entreprises détenues.</p>
<table class="tbl"><thead><tr><th>Coût</th><th>Question de rattachement</th><th>Traitement</th></tr></thead><tbody>
<tr><td>Due diligence acquisition ≥10%</td><td>Participation qualifiée ? activité des sociétés détenues ?</td><td>Analyse art. 29 al. 2–4 ; pas de « 0% » ni « prorata recettes » automatique</td></tr>
<tr><td>Conseil pour management contract</td><td>Lien direct avec prestation imposable ?</td><td>DIP direct possible si conditions art. 28 remplies</td></tr>
<tr><td>Financement / émission / prêt</td><td>Lié à activité financière exclue ou à l’ensemble de l’entreprise ?</td><td>Affectation et art. 29–30</td></tr>
<tr><td>Frais généraux</td><td>Usage commun donnant et ne donnant pas droit au DIP ?</td><td>Correction art. 30 selon utilisation, clé objective si nécessaire</td></tr>
</tbody></table>
</div>

<div class="block">
<div class="block-h"><span class="bnum">5</span><h3>Double affectation — art. 30 : l’utilisation avant le chiffre d’affaires</h3></div>
<p class="prose">Lorsqu’un bien ou un service est utilisé à la fois pour des activités donnant et ne donnant pas droit au DIP, la correction se fait <strong>en proportion de l’utilisation</strong>. Une clé de répartition doit donc être objective, plausible et documentée.</p>
<table class="comp-table"><thead><tr><th>Étape</th><th>Action</th></tr></thead><tbody><tr><td>1</td><td>Affecter directement les coûts exclusivement liés à une activité.</td></tr><tr><td>2</td><td>Isoler les coûts de participations et appliquer art. 29 al. 2–4.</td></tr><tr><td>3</td><td>Isoler les coûts liés aux prestations financières exclues.</td></tr><tr><td>4</td><td>Pour les vrais frais communs, choisir une clé reflétant l’usage : temps, ETP, coûts, surface, transactions ou recettes si ce critère est réellement représentatif.</td></tr><tr><td>5</td><td>Documenter la méthode et tester sa plausibilité d’une période à l’autre.</td></tr></tbody></table>
<div class="box afc"><div class="box-icon">🏛</div><div class="box-body"><div class="box-title">Contrôle AFC</div>Une méthode mathématiquement exacte mais économiquement inadéquate reste une mauvaise clé. Le dossier doit expliquer <strong>pourquoi</strong> la clé choisie mesure l’utilisation des inputs.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">6</span><h3>Management fees entre personnes étroitement liées</h3></div>
<p class="prose">Deux questions distinctes doivent être traitées : <strong>y a-t-il une prestation réelle ?</strong> puis <strong>quelle est sa valeur ?</strong> Pour une prestation fournie à une personne étroitement liée, l’art. 24 al. 2 retient la valeur qui aurait été convenue entre des tiers indépendants.</p>
<table class="tbl"><thead><tr><th>Pièce</th><th>Ce qu’elle aide à établir</th></tr></thead><tbody><tr><td>Contrat / scope</td><td>Prestations, destinataire, période, responsabilités</td></tr><tr><td>Livrables / rapports / time records</td><td>Exécution et volume</td></tr><tr><td>Comptabilité analytique</td><td>Coûts réellement engagés</td></tr><tr><td>Méthode de prix</td><td>Valeur comme entre tiers indépendants</td></tr><tr><td>Factures / paiements</td><td>Exigibilité et piste d’audit</td></tr></tbody></table>
<div class="box warning"><div class="box-icon">📌</div><div class="box-body"><div class="box-title">Pas de checklist jurisprudentielle inventée</div>Contrat, PV mensuels, rapports trimestriels et timesheets sont d’excellents moyens de preuve, mais le cours ne les présente pas comme « quatre critères cumulatifs imposés par un arrêt ». La preuve dépend des faits.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">7</span><h3>Groupe TVA — direction unique, pas « synergies obligatoires »</h3></div>
<p class="prose">Les entités ayant domicile, siège ou établissement stable en Suisse et réunies sous une <strong>direction unique</strong> peuvent demander l’imposition de groupe (art. 13). L’art. 15 OTVA définit la direction unique par le contrôle du comportement d’une entité au moyen de la majorité des voix, d’un contrat ou d’une autre manière.</p>
<table class="comp-table"><thead><tr><th>Point 2025+</th><th>Règle</th></tr></thead><tbody><tr><td>Périmètre</td><td>Le cercle des membres peut être choisi librement parmi les entités admissibles ; des sous-groupes sont possibles (art. 17 OTVA).</td></tr><tr><td>Représentant</td><td>Un membre établi en Suisse ou une personne non membre ayant domicile/siège en Suisse peut représenter le groupe (art. 17a OTVA).</td></tr><tr><td>Demande</td><td>La date d’effet dépend du moment où les conditions sont remplies et de l’état des décomptes/délais (art. 18 OTVA).</td></tr><tr><td>Portail</td><td>L’obligation spécifique d’utiliser le portail en ligne pour les démarches d’imposition de groupe est annoncée pour le 1er janvier 2027.</td></tr></tbody></table>
<div class="box info"><div class="box-icon">👥</div><div class="box-body"><div class="box-title">Effet principal</div>Le groupe est traité comme un seul sujet fiscal : les prestations internes ne sont pas imposées comme des opérations entre assujettis distincts. Les données internes restent indispensables pour consolider le décompte et répartir le DIP.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">8</span><h3>Groupe TVA — responsabilité solidaire et sortie</h3></div>
<p class="prose">Les membres répondent solidairement des créances d’impôt, intérêts et frais nés pendant leur appartenance, sous réserve des règles légales de sortie. Les <strong>amendes</strong> ne font pas partie de cette responsabilité solidaire (art. 15 al. 1 let. c LTVA ; art. 22 OTVA).</p>
<div class="box danger"><div class="box-icon">⚠️</div><div class="box-body"><div class="box-title">Sortir ne purge pas toujours le passé</div>Un membre ne peut pas se soustraire à la responsabilité solidaire par une sortie lorsque, notamment, une poursuite a été engagée, qu’une reprise a été faite valoir au moyen d’une notification d’estimation ou qu’un contrôle art. 78 a été annoncé.</div></div>
<div class="box info"><div class="box-icon">👤</div><div class="box-body"><div class="box-title">Représentant ≠ débiteur solidaire par fonction</div>La fonction de représentant organise la relation avec l’AFC. La solidarité découle du statut de membre et des règles légales ; depuis 2025, un représentant peut même être une personne non membre établie en Suisse.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">9</span><h3>Share deal, asset deal et procédure de déclaration art. 38</h3></div>
<table class="comp-table"><thead><tr><th>Opération</th><th>TVA</th><th>Contrôle</th></tr></thead><tbody><tr><td>Share deal</td><td>Opération sur titres / participation ; art. 29 pour le DIP des coûts qualifiés</td><td>SPA, participation ≥10%, coûts de transaction</td></tr><tr><td>Asset deal isolé</td><td>Qualifier chaque actif / prestation</td><td>Stocks, machines, immeubles, incorporels</td></tr><tr><td>Patrimoine / branche / restructuration</td><td>Tester art. 38</td><td>Assujettissement des parties, nature du transfert, seuil / lien étroit</td></tr></tbody></table>
<p class="prose">La procédure de déclaration est obligatoire notamment dans les situations visées par l’art. 38 lorsque les conditions du transfert sont remplies et que l’impôt calculé au taux légal sur le prix d’aliénation dépasse CHF 10’000, ou lorsque le transfert est effectué à une personne étroitement liée.</p>
<div class="box ok"><div class="box-icon">🧾</div><div class="box-body"><div class="box-title">Formulaire 764 — état 17.11.2025</div>Le formulaire n° 764 révisé doit être utilisé pour les transactions patrimoniales relevant de la procédure obligatoire ou facultative. En cas d’application <strong>obligatoire</strong>, les signatures des parties ne sont plus nécessaires ; en cas d’application <strong>facultative</strong>, les signatures juridiquement contraignantes des deux parties restent nécessaires. Le formulaire est transmis avec le décompte selon la procédure AFC en vigueur.</div></div>
<div class="box info"><div class="box-icon">🔁</div><div class="box-body"><div class="box-title">Chez l’acquéreur</div>Pour les valeurs transférées, l’acquéreur reprend la base de calcul et le coefficient applicable à la déduction de l’impôt préalable de l’aliénateur (art. 38 al. 4), avec contrôle ultérieur des changements d’affectation.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">10</span><h3>Acquisitions étrangères dans une holding</h3></div>
<p class="prose">Une facture étrangère n’est pas automatiquement « reverse charge ». Pour un SaaS, conseil ou autre service soumis au principe du destinataire, vérifier la catégorie de l’art. 45, le lieu, le statut du fournisseur et l’absence d’exclusion/exonération. Une holding inscrite déclare les acquisitions concernées ; le DIP éventuel dépend ensuite de l’affectation.</p>
<div class="box fidu"><div class="box-icon">💻</div><div class="box-body"><div class="box-title">Réflexe comptable</div>Facture étrangère → nature du service → art. 8 → art. 45 → montant CHF / période → impôt sur les acquisitions → DIP selon art. 28–30. M06 reste le module de référence pour la territorialité.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">11</span><h3>Contrôle AFC — notification d’estimation et contestation</h3></div>
<p class="prose">Un contrôle TVA est clos dans les 360 jours suivant son annonce écrite par une <strong>notification d’estimation</strong>, qui fixe la créance fiscale pour les périodes contrôlées. La notification et les périodes concernées peuvent entrer en force par <strong>reconnaissance écrite ou paiement sans réserve</strong> (art. 43 al. 1 let. b).</p>
<div class="box danger"><div class="box-icon">🛑</div><div class="box-body"><div class="box-title">Ne pas enseigner « seule une décision formelle est contraignante »</div>Si le contribuable n’est pas d’accord avec la notification d’estimation, il peut demander une décision selon l’art. 82. Une décision peut ensuite faire l’objet d’une réclamation dans le délai légal de 30 jours (art. 83). Payer sans réserve tout en voulant contester ensuite est donc un mauvais réflexe procédural.</div></div>
</div>

<div class="block">
<div class="block-h"><span class="bnum">12</span><h3>Mini-contrôle — 20 flux holding à classifier</h3></div>
<p class="prose">Pour chaque ligne, écrivez avant toute correction : <strong>qualification → article → traitement TVA → DIP → preuve</strong>.</p>
<table class="comp-table"><thead><tr><th>#</th><th>Flux</th><th>Réponse courte</th></tr></thead><tbody>
<tr><td>1</td><td>Dividende filiale CH</td><td>Art. 18 al. 2 let. f ; art. 33 al. 1 ; pas de réduction automatique du DIP</td></tr>
<tr><td>2</td><td>Intérêt prêt intragroupe</td><td>Art. 21 al. 2 ch. 19 ; activité financière exclue à affecter</td></tr>
<tr><td>3</td><td>Management fee CH</td><td>Prestation imposable si réelle ; art. 24 al. 2 si personne liée</td></tr>
<tr><td>4</td><td>Refacturation IT sans marge</td><td>Qualifier la prestation ; marge zéro ≠ hors TVA</td></tr>
<tr><td>5</td><td>Acquisition participation 100%</td><td>Art. 29 al. 2–4 pour les coûts de participation</td></tr>
<tr><td>6</td><td>Vente participation</td><td>Titres / participation ; art. 29 pour coûts qualifiés</td></tr>
<tr><td>7</td><td>Due diligence acquisition</td><td>Affectation art. 29, pas prorata dividendes automatique</td></tr>
<tr><td>8</td><td>Conseil management contract</td><td>DIP direct possible si lien exclusif à activité donnant droit</td></tr>
<tr><td>9</td><td>Cash-pool</td><td>Qualifier service / crédit / simple mouvement financier</td></tr>
<tr><td>10</td><td>Garantie rémunérée</td><td>Qualifier finance / service ; art. 24 si personne liée</td></tr>
<tr><td>11</td><td>SaaS étranger art. 8 al. 1</td><td>Tester art. 45 ; DIP selon affectation</td></tr>
<tr><td>12</td><td>Flux entre membres groupe TVA</td><td>Interne au sujet fiscal unique ; suivi analytique</td></tr>
<tr><td>13</td><td>Entrée membre dans groupe</td><td>Art. 18/20 OTVA : date, décomptes non remis, délais</td></tr>
<tr><td>14</td><td>Sortie membre</td><td>Date + flux devenant externes + responsabilité passée</td></tr>
<tr><td>15</td><td>Représentant non membre CH</td><td>Possible depuis art. 17a OTVA</td></tr>
<tr><td>16</td><td>Vente branche à filiale liée</td><td>Tester procédure obligatoire art. 38</td></tr>
<tr><td>17</td><td>Procédure art. 38 obligatoire</td><td>Formulaire 764 ; signatures non nécessaires depuis 17.11.2025</td></tr>
<tr><td>18</td><td>Procédure art. 38 facultative</td><td>Formulaire 764 ; signatures des deux parties requises</td></tr>
<tr><td>19</td><td>Notification d’estimation contestée</td><td>Ne pas payer sans réserve ; demander décision art. 82</td></tr>
<tr><td>20</td><td>Décision AFC contestée</td><td>Réclamation art. 83 dans les 30 jours</td></tr>
</tbody></table>
<div class="sec-nav"><button class="btn btn-g" disabled>← Début</button><button class="btn btn-p" onclick="NAV.go('legis')">Législation &amp; Sources →</button></div>
</div>
'''
sub(r'<div class="section active" id="sec-theory">.*?(?=<div class="section" id="sec-legis">)',theory,'theory rewrite')

# ------------------------------------------------------------------
# SECTION B — sources, current-law hierarchy
# ------------------------------------------------------------------
legis='''<div class="section" id="sec-legis">
<div class="hero"><div class="hero-eye">Section B · Législation &amp; Sources</div><div class="hero-h">Sources officielles à utiliser pour un dossier holding</div><div class="hero-p">Sélection contrôlée au 07.09.2026. Priorité : loi et ordonnance en vigueur, puis pratique AFC applicable, puis jurisprudence pertinente dont le lien avec le cas a été vérifié.</div><div class="hero-chips"><span class="chip">📜 LTVA</span><span class="chip">📗 OTVA</span><span class="chip">🏛 AFC</span><span class="chip">⚖️ TF / TAF vérifiés</span></div></div>
<div class="block"><div class="block-h"><span class="bnum">1</span><h3>LTVA — articles centraux</h3></div>
<table class="comp-table"><thead><tr><th>Article</th><th>Usage M07</th></tr></thead><tbody><tr><td>10 al. 1ter</td><td>Participations qualifiées = activité entrepreneuriale</td></tr><tr><td>11</td><td>Renonciation à la libération / assujettissement volontaire</td></tr><tr><td>13</td><td>Imposition de groupe</td></tr><tr><td>18 al. 2 let. f</td><td>Dividendes : pas une contre-prestation</td></tr><tr><td>21 al. 2 ch. 19</td><td>Opérations financières exclues</td></tr><tr><td>24 al. 2</td><td>Valeur entre personnes étroitement liées</td></tr><tr><td>29 al. 2–4</td><td>Participations et DIP holding</td></tr><tr><td>30</td><td>Double affectation</td></tr><tr><td>33</td><td>Éléments hors contre-prestation et réduction DIP</td></tr><tr><td>38</td><td>Procédure de déclaration</td></tr><tr><td>43, 78, 82–83</td><td>Contrôle, notification, décision et réclamation</td></tr></tbody></table>
<div class="leg-links"><a class="leg-link" href="https://www.fedlex.admin.ch/eli/cc/2009/615/fr" target="_blank" rel="noopener noreferrer">📄 LTVA — Fedlex</a></div></div>
<div class="block"><div class="block-h"><span class="bnum">2</span><h3>OTVA — groupe et procédure</h3></div><p class="prose">Pour M07, lire notamment les art. 15–22 OTVA : direction unique, membres, constitution, représentation, demande, modifications et responsabilité solidaire. La révision 2025 a introduit notamment l’art. 17a sur la représentation et a modernisé les règles de date d’effet.</p><div class="leg-links"><a class="leg-link" href="https://www.fedlex.admin.ch/eli/cc/2009/828/fr" target="_blank" rel="noopener noreferrer">📄 OTVA — Fedlex</a><a class="leg-link" href="https://www.estv.admin.ch/fr/revision-partielle-ltva-otva" target="_blank" rel="noopener noreferrer">🆕 Révision 2025 AFC</a></div></div>
<div class="block"><div class="block-h"><span class="bnum">3</span><h3>Pratique AFC à vérifier dans chaque dossier</h3></div>
<div class="leg-card"><div class="leg-icon li-green">🏛</div><div><div class="leg-title">Assujettissement et participations</div><div class="leg-desc">Vérifier le seuil, la renonciation à la libération et l’activité entrepreneuriale avant l’inscription.</div><div class="leg-links"><a class="leg-link" href="https://www.estv.admin.ch/fr/assujettissement-a-la-tva" target="_blank" rel="noopener noreferrer">AFC — Assujettissement</a></div></div></div>
<div class="leg-card"><div class="leg-icon li-green">🧾</div><div><div class="leg-title">Procédure de déclaration — formulaire 764</div><div class="leg-desc">Version révisée publiée le 17.11.2025 ; règles de signature différentes entre application obligatoire et facultative.</div><div class="leg-links"><a class="leg-link" href="https://www.estv.admin.ch/fr/newnsb/Os-oY1FEYEzWtOce1tKdC" target="_blank" rel="noopener noreferrer">AFC — Formulaire 764</a></div></div></div>
<div class="leg-card"><div class="leg-icon li-green">🔎</div><div><div class="leg-title">Contrôle TVA</div><div class="leg-desc">Notification d’estimation, reconnaissance écrite, paiement sans réserve et demande de décision.</div><div class="leg-links"><a class="leg-link" href="https://www.estv.admin.ch/fr/deroulement-dun-controle-tva" target="_blank" rel="noopener noreferrer">AFC — Déroulement d’un contrôle</a></div></div></div>
</div>
<div class="block"><div class="block-h"><span class="bnum">4</span><h3>Jurisprudence : utiliser seulement une référence vérifiée</h3></div><div class="box warning"><div class="box-icon">⚖️</div><div class="box-body"><div class="box-title">Règle du cours</div>M07 ne transforme plus des numéros d’arrêts en slogans. Avant de citer TF/TAF dans une prise de position : ouvrir le jugement, vérifier les faits, la loi applicable dans le temps, le considérant précis et sa pertinence pour le dossier. Les anciennes références non vérifiées aux « quatre critères management fees », au « groupe TVA anti-abus » et au « prorata holding » ont été retirées.</div></div><div class="leg-links"><a class="leg-link" href="https://www.bger.ch/fr/home.html" target="_blank" rel="noopener noreferrer">Tribunal fédéral</a><a class="leg-link" href="https://www.bvger.ch/fr/jurisprudence" target="_blank" rel="noopener noreferrer">Tribunal administratif fédéral</a></div></div>
<div class="sec-nav"><button class="btn btn-g" onclick="NAV.go('theory')">← Théorie</button><button class="btn btn-p" onclick="NAV.go('cases')">Cas pratiques →</button></div>
</div>
'''
sub(r'<div class="section" id="sec-legis">.*?(?=<div class="section" id="sec-cases">)',legis,'legis rewrite')

# ------------------------------------------------------------------
# SECTION C — 8 corrected professional cases
# ------------------------------------------------------------------
cases='''<div class="section" id="sec-cases">
<div class="hero"><div class="hero-eye">Section C · Cas pratiques</div><div class="hero-h">8 cas — qualification, DIP, groupe, art. 38 et contrôle</div><div class="hero-p">Chaque cas impose le même réflexe : faits → article → traitement → preuve. Les réponses ne supposent jamais qu’un dividende réduit mécaniquement le DIP.</div><div class="hero-chips"><span class="chip">🟢 Cas 1–2</span><span class="chip">🟡 Cas 3–6</span><span class="chip">🔴 Cas 7–8</span></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">1</div><div class="case-meta"><div class="case-title">Alpha Holding SA — participations et assujettissement</div><div class="case-sub">art. 10 al. 1ter · art. 11 · art. 29</div></div></div><div class="case-body"><div class="scenario">Alpha détient 100% de deux filiales suisses, ne facture aucun service et reçoit CHF 600’000 de dividendes.</div><div class="step" id="c1s1"><div class="step-q"><span class="step-qn">Q1</span> La détention des participations est-elle une activité entrepreneuriale TVA ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c1s1',this,false,'Non. L’art. 10 al. 1ter qualifie les participations visées à l’art. 29 al. 2–3 d’activité entrepreneuriale.')">A) Non, car seuls des dividendes sont reçus</button><button class="opt" onclick="CASES.answer('c1s1',this,true,'Correct. Les participations qualifiées sont expressément une activité entrepreneuriale.')">B) Oui, pour les participations qualifiées visées par l’art. 29</button></div><div class="step-expl" id="c1s1-expl">Les participations de 10% au moins répondant à l’art. 29 al. 3 entrent dans l’activité entrepreneuriale selon l’art. 10 al. 1ter.<span class="art-tag">art. 10 al. 1ter · 29 al. 3 LTVA</span></div></div><div class="step" id="c1s2"><div class="step-q"><span class="step-qn">Q2</span> Les CHF 600’000 de dividendes déclenchent-ils à eux seuls l’assujettissement obligatoire par le seuil de CHF 100’000 ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c1s2',this,false,'Non. Le dividende n’est pas une contre-prestation.')">A) Oui</button><button class="opt" onclick="CASES.answer('c1s2',this,true,'Correct. Ils ne sont pas une contre-prestation. Une inscription volontaire doit cependant être examinée séparément.')">B) Non ; examiner séparément une inscription volontaire</button></div><div class="step-expl" id="c1s2-expl">Le seuil vise le chiffre d’affaires mondial provenant de prestations non exclues. Les dividendes ne sont pas une contre-prestation. L’art. 11 peut être pertinent pour une inscription volontaire.<span class="art-tag">art. 10–11 · 18 al. 2 let. f</span></div></div></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">2</div><div class="case-meta"><div class="case-title">Beta Holding SA — management fees à une filiale liée</div><div class="case-sub">art. 18 · art. 24 al. 2</div></div></div><div class="case-body"><div class="scenario">Beta facture CHF 225’000 de direction, RH et IT à sa filiale. Les sociétés sont étroitement liées.</div><div class="step" id="c2s1"><div class="step-q"><span class="step-qn">Q1</span> Quel test vient avant le calcul de TVA ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c2s1',this,true,'Correct. Il faut établir l’existence et le bénéficiaire de la prestation, puis sa valeur entre tiers indépendants.')">A) Prestation réelle + bénéficiaire + valeur de pleine concurrence</button><button class="opt" onclick="CASES.answer('c2s1',this,false,'Non. Une facture seule ne prouve pas tout le contenu économique.')">B) Vérifier uniquement la facture</button></div><div class="step-expl" id="c2s1-expl">L’art. 24 al. 2 impose la valeur qui aurait été convenue entre tiers indépendants pour une prestation à une personne étroitement liée.<span class="art-tag">art. 24 al. 2 LTVA</span></div></div><div class="step" id="c2s2"><div class="step-q"><span class="step-qn">Q2</span> Existe-t-il une liste légale universelle de « quatre documents cumulatifs » pour valider tout management fee ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c2s2',this,false,'Non. Le dossier de preuve dépend des faits.')">A) Oui : contrat + PV mensuel + rapport trimestriel + benchmark, toujours</button><button class="opt" onclick="CASES.answer('c2s2',this,true,'Correct. Ces pièces sont utiles, mais la preuve est un faisceau adapté au service concret.')">B) Non ; constituer un faisceau de preuves adapté</button></div><div class="step-expl" id="c2s2-expl">Contrat, livrables, temps, comptes analytiques et méthode de prix sont des preuves fortes, sans devenir une checklist jurisprudentielle inventée.<span class="art-tag">art. 24 al. 2 · preuve des faits</span></div></div></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">3</div><div class="case-meta"><div class="case-title">Gamma Holding SA — dividendes et DIP</div><div class="case-sub">art. 18 al. 2 let. f · art. 33 al. 1</div></div></div><div class="case-body"><div class="scenario">Gamma reçoit CHF 500’000 de dividendes et facture CHF 200’000 de management services. Une facture de conseil de CHF 30’000 HT concerne exclusivement les services imposables.</div><div class="step" id="c3s1"><div class="step-q"><span class="step-qn">Q1</span> Faut-il réduire le DIP de cette facture à 200/(200+500)=28,6% uniquement parce que Gamma reçoit des dividendes ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c3s1',this,false,'Non. Les dividendes n’entraînent pas une réduction du DIP du seul fait de leur réception.')">A) Oui</button><button class="opt" onclick="CASES.answer('c3s1',this,true,'Correct. La facture est directement affectée à une activité imposable ; les dividendes ne déclenchent pas une réduction art. 33 al. 1.')">B) Non</button></div><div class="step-expl" id="c3s1-expl">L’affectation directe prime. L’art. 33 al. 1 précise que les dividendes, comme éléments hors contre-prestation visés à l’art. 18 al. 2 let. d–l, n’influencent en principe pas le montant du DIP.<span class="art-tag">art. 28 · 33 al. 1 LTVA</span></div></div><div class="step" id="c3s2"><div class="step-q"><span class="step-qn">Q2</span> Une facture de banque exclusivement liée à une activité de crédit exclue suit-elle le même traitement ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c3s2',this,false,'Non. Une activité financière exclue doit être distinguée des dividendes.')">A) Oui, toujours DIP intégral</button><button class="opt" onclick="CASES.answer('c3s2',this,true,'Correct. Les coûts liés à une prestation financière exclue doivent être analysés selon art. 29–30.')">B) Non ; analyser l’exclusion financière et l’affectation</button></div><div class="step-expl" id="c3s2-expl">Dividende hors contre-prestation et prestation financière exclue ne sont pas la même catégorie.<span class="art-tag">art. 21 al. 2 ch. 19 · 29–30</span></div></div></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">4</div><div class="case-meta"><div class="case-title">Delta Holding SA — due diligence d’une participation</div><div class="case-sub">art. 29 al. 2–4</div></div></div><div class="case-body"><div class="scenario">Delta acquiert 80% d’une société opérationnelle. La due diligence coûte CHF 180’000 HT + TVA. Delta détient aussi une activité financière exclue.</div><div class="step" id="c4s1"><div class="step-q"><span class="step-qn">Q1</span> Peut-on imposer d’office un prorata « recettes imposables / toutes recettes » à la TVA sur la due diligence ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c4s1',this,false,'Non. Les coûts de participation ont un régime spécifique art. 29 al. 2–4.')">A) Oui</button><button class="opt" onclick="CASES.answer('c4s1',this,true,'Correct. Il faut analyser la participation qualifiée, l’activité entrepreneuriale donnant droit au DIP et l’activité des entreprises détenues.')">B) Non</button></div><div class="step-expl" id="c4s1-expl">Le droit au DIP sur des coûts d’acquisition / détention / aliénation d’une participation qualifiée ne se résume pas à un ratio de dividendes.<span class="art-tag">art. 29 al. 2–4</span></div></div><div class="step" id="c4s2"><div class="step-q"><span class="step-qn">Q2</span> Quel document interne est le plus utile ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c4s2',this,true,'Correct. Il faut documenter le rattachement des coûts et la base juridique du DIP.')">A) Une note d’affectation M&amp;A reliant factures, participation et activités</button><button class="opt" onclick="CASES.answer('c4s2',this,false,'Non. Le montant du dividende n’est pas à lui seul une clé de DIP.')">B) Un tableau des dividendes uniquement</button></div><div class="step-expl" id="c4s2-expl">SPA, mandat, factures détaillées et note art. 29 rendent le dossier contrôlable.<span class="art-tag">art. 29–30</span></div></div></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">5</div><div class="case-meta"><div class="case-title">Epsilon Group — formation d’un groupe TVA</div><div class="case-sub">art. 13 LTVA · art. 15–18 OTVA</div></div></div><div class="case-body"><div class="scenario">Epsilon Holding SA détient 100% des voix de Tech SA et 80% des voix d’Immo SA. Les trois entités ont leur siège en Suisse.</div><div class="step" id="c5s1"><div class="step-q"><span class="step-qn">Q1</span> Quel élément juridique démontre ici la direction unique ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c5s1',this,true,'Correct. La majorité des voix permet le contrôle du comportement des filiales.')">A) La majorité des droits de vote</button><button class="opt" onclick="CASES.answer('c5s1',this,false,'Non. Des synergies opérationnelles ne remplacent pas le test de direction unique.')">B) Le fait qu’elles utilisent le même logiciel</button></div><div class="step-expl" id="c5s1-expl">L’art. 15 OTVA définit la direction unique par la majorité des voix, le contrat ou tout autre moyen de contrôle.<span class="art-tag">art. 13 LTVA · 15 OTVA</span></div></div><div class="step" id="c5s2"><div class="step-q"><span class="step-qn">Q2</span> Le représentant doit-il obligatoirement être un membre du groupe ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c5s2',this,false,'Non depuis l’art. 17a OTVA.')">A) Oui</button><button class="opt" onclick="CASES.answer('c5s2',this,true,'Correct. Une personne non membre avec domicile/siège en Suisse peut représenter le groupe.')">B) Non</button></div><div class="step-expl" id="c5s2-expl">L’art. 17a OTVA permet un représentant non membre établi en Suisse.<span class="art-tag">art. 17a OTVA</span></div></div></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">6</div><div class="case-meta"><div class="case-title">Zeta Holding SA — SaaS étranger</div><div class="case-sub">art. 8 al. 1 · art. 45</div></div></div><div class="case-body"><div class="scenario">Zeta, inscrite TVA, achète CHF 85’000 de SaaS à un fournisseur étranger non inscrit en Suisse. Le service est localisé au siège suisse du destinataire selon art. 8 al. 1.</div><div class="step" id="c6s1"><div class="step-q"><span class="step-qn">Q1</span> Quel est le réflexe ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c6s1',this,true,'Correct. Le service entre dans le test de l’impôt sur les acquisitions.')">A) Tester et déclarer l’impôt sur les acquisitions art. 45</button><button class="opt" onclick="CASES.answer('c6s1',this,false,'Non. Une facture étrangère n’est pas une importation de biens OFDF.')">B) TVA d’importation OFDF</button></div><div class="step-expl" id="c6s1-expl">Une entreprise inscrite déclare les acquisitions visées par l’art. 45. Le DIP correspondant est déductible seulement selon les conditions et l’affectation.<span class="art-tag">art. 45 · art. 28–30</span></div></div><div class="step" id="c6s2"><div class="step-q"><span class="step-qn">Q2</span> Le fait que le fournisseur soit étranger suffit-il pour auto-imposer toute facture ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c6s2',this,false,'Non. Il faut une catégorie légale visée par art. 45 et une localisation pertinente.')">A) Oui</button><button class="opt" onclick="CASES.answer('c6s2',this,true,'Correct. Nature, lieu, fournisseur et exclusions doivent être vérifiés.')">B) Non</button></div><div class="step-expl" id="c6s2-expl">La qualification précède le calcul.<span class="art-tag">art. 45 LTVA</span></div></div></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">7</div><div class="case-meta"><div class="case-title">Theta Group — transfert d’une branche à une société liée</div><div class="case-sub">art. 38 · formulaire 764</div></div></div><div class="case-body"><div class="scenario">Theta transfère une branche opérationnelle à une filiale suisse liée. Les deux parties sont assujetties. L’impôt calculé au taux légal sur le prix d’aliénation dépasserait CHF 10’000.</div><div class="step" id="c7s1"><div class="step-q"><span class="step-qn">Q1</span> Quelle procédure faut-il tester avant la facturation ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c7s1',this,true,'Correct. Les conditions décrites placent le dossier dans le test de la procédure de déclaration obligatoire.')">A) Procédure de déclaration art. 38</button><button class="opt" onclick="CASES.answer('c7s1',this,false,'Non. Une autorisation orale ne remplace pas la procédure.')">B) Une autorisation orale de l’AFC</button></div><div class="step-expl" id="c7s1-expl">Le transfert d’un patrimoine / d’une branche dans les situations de l’art. 38 peut imposer la procédure de déclaration ; le lien étroit est lui aussi un déclencheur légal.<span class="art-tag">art. 38 LTVA</span></div></div><div class="step" id="c7s2"><div class="step-q"><span class="step-qn">Q2</span> Depuis le 17.11.2025, les signatures des deux parties sont-elles requises sur le formulaire 764 dans un cas obligatoire ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c7s2',this,false,'Non pour l’application obligatoire depuis la révision du formulaire.')">A) Oui</button><button class="opt" onclick="CASES.answer('c7s2',this,true,'Correct. Elles restent requises pour la procédure facultative, pas pour l’application obligatoire.')">B) Non</button></div><div class="step-expl" id="c7s2-expl">La communication AFC du 17 novembre 2025 distingue explicitement application obligatoire et facultative.<span class="art-tag">Formulaire 764 · 17.11.2025</span></div></div></div></div>

<div class="case-card"><div class="case-head"><div class="case-n">8</div><div class="case-meta"><div class="case-title">Omega Holding SA — contrôle AFC</div><div class="case-sub">art. 43 · 78 · 82–83</div></div></div><div class="case-body"><div class="scenario">Après contrôle, Omega reçoit une notification d’estimation prévoyant une reprise de CHF 31’493 plus intérêts. Elle conteste une partie de la méthode de calcul.</div><div class="step" id="c8s1"><div class="step-q"><span class="step-qn">Q1</span> Est-il prudent de payer immédiatement la totalité sans réserve tout en voulant contester ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c8s1',this,false,'Non. Le paiement sans réserve peut faire entrer en force la créance fixée par la notification.')">A) Oui</button><button class="opt" onclick="CASES.answer('c8s1',this,true,'Correct. Il faut préserver la voie de contestation et formaliser le désaccord.')">B) Non</button></div><div class="step-expl" id="c8s1-expl">La notification d’estimation et les périodes contrôlées entrent en force par reconnaissance écrite ou paiement sans réserve.<span class="art-tag">art. 43 al. 1 let. b LTVA</span></div></div><div class="step" id="c8s2"><div class="step-q"><span class="step-qn">Q2</span> Que peut faire Omega si elle n’est pas d’accord avec la notification d’estimation ?</div><div class="step-opts"><button class="opt" onclick="CASES.answer('c8s2',this,true,'Correct. L’AFC indique qu’un contribuable en désaccord peut demander une décision selon l’art. 82.')">A) Demander une décision art. 82, puis utiliser la réclamation art. 83 dans le délai légal</button><button class="opt" onclick="CASES.answer('c8s2',this,false,'Non. La notification peut entrer en force avant une décision formelle par reconnaissance/paiement sans réserve.')">B) Attendre : seule une décision formelle peut jamais devenir contraignante</button></div><div class="step-expl" id="c8s2-expl">Après décision, la réclamation doit être formée dans les 30 jours selon l’art. 83. Le dossier doit distinguer notification d’estimation, décision et réclamation.<span class="art-tag">art. 82–83 LTVA</span></div></div><div class="calc"><div class="calc-title">Position à documenter</div><div class="calc-row"><span class="calc-label">Reprise contestée</span><span class="calc-val">CHF 31’493</span></div><div class="calc-row danger"><span class="calc-label">Intérêts moratoires</span><span class="calc-val">à calculer selon période / taux DFF</span></div><div class="calc-row hl"><span class="calc-label">Total</span><span class="calc-val">CHF 31’493 + intérêts calculés</span></div></div></div></div>
<div class="sec-nav"><button class="btn btn-g" onclick="NAV.go('legis')">← Législation</button><button class="btn btn-p" onclick="NAV.go('errors')">Erreurs fréquentes →</button></div>
</div>
'''
sub(r'<div class="section" id="sec-cases">.*?(?=<div class="section" id="sec-errors">)',cases,'cases rewrite')

# ------------------------------------------------------------------
# SECTION D — corrected errors
# ------------------------------------------------------------------
errors='''<div class="section" id="sec-errors">
<div class="hero"><div class="hero-eye">Section D · Erreurs fréquentes</div><div class="hero-h">8 erreurs critiques — holdings &amp; groupes TVA</div><div class="hero-p">Les erreurs ci-dessous sont formulées sans montants de reprise inventés : l’impact réel dépend toujours des périodes, de l’affectation et du taux d’intérêt applicable.</div><div class="hero-chips"><span class="chip">⚠️ 8 erreurs</span><span class="chip">🧾 preuve</span><span class="chip">🏛 procédure</span></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">📊</div><div><div class="err-htitle">1 — Mettre les dividendes automatiquement au dénominateur d’un prorata</div></div></div><div class="err-body"><div class="err-wrong">❌ Réduire le DIP uniquement parce que des dividendes ont été encaissés.</div><div class="err-right">✅ Art. 33 al. 1 : les dividendes ne réduisent pas en principe le DIP. Analyser l’utilisation réelle des coûts et l’art. 29 pour les participations.</div></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">🏢</div><div><div class="err-htitle">2 — Considérer une holding de participations comme non entrepreneuriale par nature</div></div></div><div class="err-body"><div class="err-wrong">❌ « Pas de management fees = pas d’entreprise TVA ».</div><div class="err-right">✅ Les participations qualifiées visées à l’art. 29 constituent une activité entrepreneuriale selon art. 10 al. 1ter ; distinguer ensuite assujettissement obligatoire et volontaire.</div></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">📄</div><div><div class="err-htitle">3 — Facturer un management fee lié sans prouver prestation et valeur</div></div></div><div class="err-body"><div class="err-wrong">❌ Facture annuelle forfaitaire sans scope, livrables ni méthode de prix.</div><div class="err-right">✅ Établir l’échange de prestations et documenter la valeur comme entre tiers indépendants selon art. 24 al. 2. Il n’existe pas une checklist universelle de quatre pièces.</div></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">👥</div><div><div class="err-htitle">4 — Remplacer la « direction unique » par une notion vague de synergies</div></div></div><div class="err-body"><div class="err-wrong">❌ Exiger le même secteur, les mêmes locaux ou une motivation non fiscale.</div><div class="err-right">✅ Tester le contrôle du comportement par majorité des voix, contrat ou autre moyen selon art. 15 OTVA, puis le périmètre admissible.</div></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">👤</div><div><div class="err-htitle">5 — Croire que la solidarité existe parce qu’une entité est représentante</div></div></div><div class="err-body"><div class="err-wrong">❌ « Le représentant paie toutes les dettes du groupe ».</div><div class="err-right">✅ La solidarité découle du statut de membre et de l’art. 15 LTVA / 22 OTVA. Un représentant non membre établi en Suisse est possible depuis art. 17a OTVA.</div></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">🔄</div><div><div class="err-htitle">6 — Attendre une « confirmation écrite AFC » avant d’appliquer art. 38</div></div></div><div class="err-body"><div class="err-wrong">❌ Présenter la procédure comme une autorisation discrétionnaire.</div><div class="err-right">✅ Tester les conditions légales, déclarer avec le décompte et utiliser le formulaire 764. Depuis 17.11.2025, pas de signatures pour l’application obligatoire ; signatures des deux parties pour l’application facultative.</div></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">💻</div><div><div class="err-htitle">7 — Traiter toute facture étrangère comme impôt sur les acquisitions</div></div></div><div class="err-body"><div class="err-wrong">❌ « Fournisseur étranger = 8,1% ch. 383 ».</div><div class="err-right">✅ Vérifier nature, lieu, catégorie art. 45, statut du fournisseur et exclusion/exonération. Puis seulement calculer et traiter le DIP.</div></div></div>
<div class="err-block"><div class="err-head"><div class="err-icon">🛑</div><div><div class="err-htitle">8 — Payer sans réserve une notification d’estimation contestée</div></div></div><div class="err-body"><div class="err-wrong">❌ Payer puis supposer qu’une contestation reste toujours ouverte.</div><div class="err-right">✅ Reconnaissance écrite ou paiement sans réserve peut faire entrer la créance en force. En désaccord, demander une décision art. 82 et respecter ensuite le délai de réclamation art. 83.</div></div></div>
<div class="sec-nav"><button class="btn btn-g" onclick="NAV.go('cases')">← Cas pratiques</button><button class="btn btn-p" onclick="NAV.go('quiz')">Autotest QCM →</button></div>
</div>
'''
sub(r'<div class="section" id="sec-errors">.*?(?=<div class="section" id="sec-quiz">)',errors,'errors rewrite')

# Quiz presentation consistency
rep('30 questions · Format professionnel · Timer 25 min','35 questions · Format professionnel · Timer 30 min','quiz heading')
rep('Seuil de validation : 75% (23/30). Auto-submit à 0:00.','Seuil de validation : 75% (27/35). Auto-submit à 0:00.','quiz threshold')
rep('<span class="chip">⏱ 25 min</span>','<span class="chip">⏱ 30 min</span>','quiz time chip')
rep('Question 1 / 30','Question 1 / 35','quiz initial counter')
rep('25:00','30:00','quiz initial timer')
rep('SECTION E — QUIZ 30 QUESTIONS','SECTION E — QUIZ 35 QUESTIONS','quiz comment')
rep('25 flashcards Holdings — 4 catégories · SM-2','30 flashcards Holdings — 5 catégories · SM-2','flash heading')
rep('<span class="chip">📚 4 catégories</span>','<span class="chip">📚 5 catégories</span>','flash category chip')

# ------------------------------------------------------------------
# SECTION G — corrected vocabulary
# ------------------------------------------------------------------
vocab='''<div class="section" id="sec-vocab">
<div class="hero"><div class="hero-eye">Section G · Vocabulaire professionnel</div><div class="hero-h">Terminologie holdings TVA — FR / Deutsch</div><div class="hero-p">Vocabulaire conçu pour distinguer les catégories qui sont souvent mélangées dans les dossiers de groupes.</div></div>
<div class="vocab-grid">
<div class="vocab-card"><div class="vfr">Participation qualifiée</div><div class="vde">Qualifizierte Beteiligung</div><div class="vdef">Participation au sens de l’art. 29 ; une part de 10% au moins du capital est notamment considérée comme participation. Son acquisition, sa détention et son aliénation constituent une activité entrepreneuriale.</div><div class="vart">art. 10 al. 1ter · 29 al. 2–3</div></div>
<div class="vocab-card"><div class="vfr">Dividende</div><div class="vde">Dividende</div><div class="vdef">Élément ne constituant pas une contre-prestation. Il ne provoque pas, à lui seul, une réduction du DIP selon art. 33 al. 1.</div><div class="vart">art. 18 al. 2 let. f · 33 al. 1</div></div>
<div class="vocab-card"><div class="vfr">Opération financière exclue</div><div class="vde">Von der Steuer ausgenommener Finanzumsatz</div><div class="vdef">Crédit, intérêts ou opérations sur titres selon les catégories art. 21 al. 2 ch. 19. À distinguer du dividende hors contre-prestation.</div><div class="vart">art. 21 al. 2 ch. 19</div></div>
<div class="vocab-card"><div class="vfr">Assujettissement volontaire</div><div class="vde">Freiwillige Steuerpflicht</div><div class="vdef">Renonciation à la libération de l’assujettissement pour une entité exerçant une activité entrepreneuriale lorsque les conditions sont remplies.</div><div class="vart">art. 11 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Valeur entre proches</div><div class="vde">Drittpreis / Marktwert bei nahestehenden Personen</div><div class="vdef">Pour une prestation à une personne étroitement liée, contre-prestation = valeur qui aurait été convenue entre tiers indépendants.</div><div class="vart">art. 24 al. 2 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Affectation directe</div><div class="vde">Direkte Zuordnung</div><div class="vdef">Rattachement d’un input à une activité précise avant toute clé de correction des coûts mixtes.</div><div class="vart">art. 28–30 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Double affectation</div><div class="vde">Gemischte Verwendung</div><div class="vdef">Utilisation d’un input pour activités donnant et ne donnant pas droit au DIP ; correction proportionnelle à l’utilisation réelle.</div><div class="vart">art. 30 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Groupe TVA</div><div class="vde">MWST-Gruppe</div><div class="vdef">Entités admissibles établies en Suisse et réunies sous une direction unique, traitées sur demande comme un seul sujet fiscal.</div><div class="vart">art. 13 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Direction unique</div><div class="vde">Einheitliche Leitung</div><div class="vdef">Contrôle du comportement d’une entité par majorité des voix, contrat ou autre moyen.</div><div class="vart">art. 15 OTVA</div></div>
<div class="vocab-card"><div class="vfr">Représentant du groupe</div><div class="vde">Gruppenvertretung</div><div class="vdef">Membre établi en Suisse ou personne non membre ayant domicile/siège en Suisse qui représente le groupe envers l’AFC.</div><div class="vart">art. 17a OTVA</div></div>
<div class="vocab-card"><div class="vfr">Responsabilité solidaire</div><div class="vde">Solidarhaftung</div><div class="vdef">Responsabilité des membres pour les créances d’impôt, intérêts et frais nés durant l’appartenance, sauf amendes, avec règles particulières lors de la sortie.</div><div class="vart">art. 15 LTVA · 22 OTVA</div></div>
<div class="vocab-card"><div class="vfr">Procédure de déclaration</div><div class="vde">Meldeverfahren</div><div class="vdef">Mécanisme art. 38 pour certains transferts de patrimoine / restructurations, documenté avec le formulaire 764.</div><div class="vart">art. 38 LTVA · formulaire 764</div></div>
<div class="vocab-card"><div class="vfr">Notification d’estimation</div><div class="vde">Einschätzungsmitteilung</div><div class="vdef">Acte clôturant le contrôle TVA et fixant la créance fiscale pour les périodes contrôlées.</div><div class="vart">art. 78 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Paiement sans réserve</div><div class="vde">Vorbehaltlose Zahlung</div><div class="vdef">Peut entraîner l’entrée en force de la créance fixée par la notification d’estimation.</div><div class="vart">art. 43 al. 1 let. b</div></div>
<div class="vocab-card"><div class="vfr">Impôt sur les acquisitions</div><div class="vde">Bezugsteuer</div><div class="vdef">Imposition de certaines acquisitions visées à l’art. 45 ; une facture étrangère ne suffit pas à elle seule.</div><div class="vart">art. 45–49 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Share deal</div><div class="vde">Share Deal</div><div class="vdef">Transfert de titres / participations ; ne pas confondre avec le transfert d’actifs ou d’une branche.</div><div class="vart">art. 21 ch. 19 · art. 29</div></div>
<div class="vocab-card"><div class="vfr">Asset deal</div><div class="vde">Asset Deal</div><div class="vdef">Transfert d’actifs ; qualifier les éléments et tester art. 38 si un patrimoine ou une branche est transféré.</div><div class="vart">art. 38 LTVA</div></div>
<div class="vocab-card"><div class="vfr">Formulaire 764</div><div class="vde">Formular 764</div><div class="vdef">Formulaire AFC pour la procédure de déclaration ; version révisée applicable depuis le 17.11.2025.</div><div class="vart">AFC · art. 38 LTVA</div></div>
</div>
<div class="sec-nav"><button class="btn btn-g" onclick="NAV.go('memo')">← Mémo-fiches</button><button class="btn btn-p" onclick="NAV.go('cheat')">Cheatsheet AFC →</button></div>
</div>
'''
sub(r'<div class="section" id="sec-vocab">.*?(?=<div class="section" id="sec-cheat">)',vocab,'vocab rewrite')

# ------------------------------------------------------------------
# SECTION H — current cheatsheet + completion
# ------------------------------------------------------------------
cheat='''<div class="section" id="sec-cheat">
<div class="hero"><div class="hero-eye">Section H · Cheatsheet praticien</div><div class="hero-h">Holdings &amp; groupes TVA — décisions rapides</div><div class="hero-p">Révision juridique du 07.09.2026. Vérifier la pratique AFC applicable à la date du dossier avant une prise de position professionnelle.</div></div>
<div class="cheat-block"><div class="cheat-title">Holding — 6 réflexes</div><div class="cheat-grid"><div class="ci"><span class="ci-l">Participation ≥10%</span><span class="ci-v">activité entrepreneuriale · art. 10 al. 1ter</span></div><div class="ci"><span class="ci-l">Dividende</span><span class="ci-v g">art. 18 + art. 33 al. 1</span></div><div class="ci"><span class="ci-l">Intérêt / crédit</span><span class="ci-v o">art. 21 ch. 19 · affectation</span></div><div class="ci"><span class="ci-l">Coûts participation</span><span class="ci-v">art. 29 al. 2–4</span></div><div class="ci"><span class="ci-l">Coûts mixtes</span><span class="ci-v">art. 30 · clé objective</span></div><div class="ci"><span class="ci-l">Management fee lié</span><span class="ci-v">prestation réelle + art. 24 al. 2</span></div></div></div>
<div class="cheat-block"><div class="cheat-title">Dividende ≠ finance exclue</div><div class="box ok"><div class="box-icon">✅</div><div class="box-body"><strong>Dividende :</strong> hors contre-prestation et pas de réduction du DIP du seul fait de sa réception. <strong>Intérêts / crédit / titres :</strong> prestations financières généralement exclues ; leurs coûts peuvent affecter le DIP selon leur rattachement. Ne jamais fusionner ces catégories dans une ligne « hors champ = 0 DIP ».</div></div></div>
<div class="cheat-block"><div class="cheat-title">Groupe TVA 2025+</div><div class="cheat-grid"><div class="ci"><span class="ci-l">Condition centrale</span><span class="ci-v">direction unique · art. 15 OTVA</span></div><div class="ci"><span class="ci-l">Périmètre</span><span class="ci-v">choix parmi entités admissibles · art. 17</span></div><div class="ci"><span class="ci-l">Représentant</span><span class="ci-v">membre CH ou non-membre CH · art. 17a</span></div><div class="ci"><span class="ci-l">Interne groupe</span><span class="ci-v g">pas de TVA interne</span></div><div class="ci"><span class="ci-l">Solidarité</span><span class="ci-v r">impôt + intérêts + frais ; pas amendes</span></div><div class="ci"><span class="ci-l">Portail groupe</span><span class="ci-v">obligation spécifique dès 01.01.2027</span></div></div></div>
<div class="cheat-block"><div class="cheat-title">Art. 38 — procédure de déclaration</div><div class="cheat-grid"><div class="ci"><span class="ci-l">Cas obligatoire</span><span class="ci-v">tester transfert/restructuration + seuil / proche</span></div><div class="ci"><span class="ci-l">Formulaire</span><span class="ci-v">n° 764</span></div><div class="ci"><span class="ci-l">Obligatoire — signatures</span><span class="ci-v g">non requises depuis 17.11.2025</span></div><div class="ci"><span class="ci-l">Facultatif — signatures</span><span class="ci-v r">deux parties requises</span></div><div class="ci"><span class="ci-l">Acquéreur</span><span class="ci-v">reprend base + coefficient DIP art. 38 al. 4</span></div></div></div>
<div class="cheat-block"><div class="cheat-title">Contrôle AFC</div><div class="cheat-grid"><div class="ci"><span class="ci-l">Clôture contrôle</span><span class="ci-v">notification d’estimation ≤ 360 jours</span></div><div class="ci"><span class="ci-l">Entrée en force</span><span class="ci-v r">reconnaissance écrite ou paiement sans réserve</span></div><div class="ci"><span class="ci-l">Désaccord</span><span class="ci-v">demander décision art. 82</span></div><div class="ci"><span class="ci-l">Réclamation décision</span><span class="ci-v">30 jours · art. 83</span></div><div class="ci"><span class="ci-l">Intérêts</span><span class="ci-v">taux DFF applicable à la période</span></div></div></div>
<div class="cheat-block"><div class="cheat-title">Sources M07</div><div style="font-size:12.5px;line-height:2;color:#2C2C3E"><div><strong>LTVA :</strong> 10 al. 1ter · 11 · 13 · 18 · 21 ch. 19 · 24 al. 2 · 29–30 · 33 · 38 · 43 · 78 · 82–83</div><div><strong>OTVA :</strong> 15–22 pour l’imposition de groupe</div><div><strong>AFC :</strong> Assujettissement · principes de la taxe · formulaire 764 · déroulement d’un contrôle TVA</div><div><strong>Jurisprudence :</strong> citer uniquement après vérification du jugement et du considérant pertinent</div></div></div>
<div class="cheat-final" style="text-align:center;margin-top:18px"><p style="font-size:12px;color:var(--muted);margin-bottom:12px">Fin de M07 : la suite logique est <strong>M08 — Immobilier &amp; construction</strong>.</p><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><a class="btn btn-g" href="index.html" style="text-decoration:none">← Retour au cours</a><button class="btn btn-p" onclick="PROG.finish()">✓ Terminer M07</button><button class="btn btn-gold" onclick="goNextModule()">Continuer avec M08 →</button></div><div id="m07-complete" class="box ok" style="display:none;text-align:left;margin-top:16px"><div class="box-icon">✅</div><div class="box-body"><div class="box-title">M07 enregistré comme terminé</div>La progression du module est synchronisée avec le tableau de bord. Le quiz reste une validation pédagogique distincte.</div></div><p style="font-size:11px;color:var(--muted);margin-top:16px">Conception : <a href="https://www.linkedin.com/in/mariia-lobur/" target="_blank" rel="noopener noreferrer">Mariia Lobur</a> · <a href="https://github.com/mariialobur" target="_blank" rel="noopener noreferrer">GitHub</a></p></div>
<div class="sec-nav"><button class="btn btn-g" onclick="NAV.go('vocab')">← Vocabulaire</button><button class="btn btn-gold" onclick="NAV.go('theory')">⬡ Revoir M07</button></div>
</div>
'''
sub(r'<div class="section" id="sec-cheat">.*?(?=</div>\n</div>\n<script>)',cheat,'cheat rewrite')

# ------------------------------------------------------------------
# Rebuild the QCM with 35 current-law questions
# ------------------------------------------------------------------
qs=[
{"a":"art. 10 al. 1ter LTVA","q":"L’acquisition, la détention et l’aliénation de participations qualifiées constituent-elles une activité entrepreneuriale ?","o":["Non","Oui","Uniquement avec management fees","Uniquement dans un groupe TVA"],"c":1,"e":"L’art. 10 al. 1ter le prévoit expressément pour les participations visées à l’art. 29 al. 2–3."},
{"a":"art. 29 al. 3 LTVA","q":"Quel seuil de capital est expressément considéré comme participation au sens de l’art. 29 al. 3 ?","o":["1%","5%","10%","50%"],"c":2,"e":"Toute part de 10% au moins du capital est considérée comme participation, sous le cadre de l’art. 29 al. 3."},
{"a":"art. 11 LTVA","q":"Une entité entrepreneuriale sous le seuil d’assujettissement peut-elle en principe demander une inscription volontaire ?","o":["Oui, si les conditions légales sont remplies","Jamais","Seulement si elle emploie 10 personnes","Seulement après un contrôle"],"c":0,"e":"La renonciation à la libération de l’assujettissement est prévue par l’art. 11."},
{"a":"art. 10 LTVA","q":"Pour le seuil ordinaire de CHF 100’000, quel chiffre d’affaires est déterminant ?","o":["Tous les encaissements, dividendes inclus","Le CA mondial provenant de prestations qui ne sont pas exclues","Uniquement les prestations suisses","La valeur des participations"],"c":1,"e":"Le seuil se fonde sur le CA mondial provenant de prestations non exclues du champ de l’impôt."},
{"a":"art. 18 al. 2 let. f","q":"Un dividende reçu par une holding est :","o":["Une prestation imposable","Une exonération art. 23","Un élément ne constituant pas une contre-prestation","Une prestation financière art. 21 ch. 19"],"c":2,"e":"Le dividende ne constitue pas une contre-prestation TVA."},
{"a":"art. 33 al. 1 LTVA","q":"La réception d’un dividende entraîne-t-elle en principe, à elle seule, une réduction du DIP ?","o":["Oui, toujours","Non","Seulement si > CHF 100’000","Seulement en groupe TVA"],"c":1,"e":"Les éléments de l’art. 18 al. 2 let. d–l, dont les dividendes, n’influencent en principe pas le montant du DIP."},
{"a":"art. 21 al. 2 ch. 19","q":"Les intérêts d’un prêt intragroupe sont-ils la même catégorie TVA qu’un dividende ?","o":["Oui","Non, ils relèvent généralement d’une opération financière exclue","Oui si le prêt est long terme","Oui si les sociétés sont liées"],"c":1,"e":"Intérêt/crédit et dividende doivent être distingués."},
{"a":"art. 24 al. 2 LTVA","q":"Une prestation à une personne étroitement liée est évaluée selon :","o":["Le prix choisi librement sans contrôle","La valeur convenue entre tiers indépendants","Toujours les coûts sans marge","Le bénéfice de la filiale"],"c":1,"e":"Art. 24 al. 2 retient la valeur de pleine concurrence."},
{"a":"management fees","q":"Quel ordre est correct pour un management fee intragroupe ?","o":["Calculer TVA puis chercher une preuve","Établir prestation/bénéficiaire, documenter valeur, puis traiter TVA","Utiliser toujours 10% du bénéfice","Demander une autorisation AFC"],"c":1,"e":"Existence de la prestation et valeur précèdent le calcul."},
{"a":"preuve","q":"Existe-t-il une liste légale universelle de quatre pièces cumulatives pour tout management fee ?","o":["Oui","Non","Seulement depuis 2025","Seulement pour les holdings"],"c":1,"e":"Le dossier repose sur les faits : contrat, livrables, temps, coûts et méthode de prix peuvent être pertinents sans liste universelle."},
{"a":"art. 29 al. 2 LTVA","q":"Les coûts d’acquisition d’une participation qualifiée sont-ils automatiquement non déductibles ?","o":["Oui","Non, l’art. 29 al. 2 prévoit un régime dérogatoire dans l’activité entrepreneuriale donnant droit","Oui sauf groupe TVA","Oui sauf fusion"],"c":1,"e":"Art. 29 al. 2 doit être analysé avant tout refus de DIP."},
{"a":"art. 29 al. 4 LTVA","q":"Pour déterminer le DIP déductible d’une société holding, peut-on prendre en compte l’activité des entreprises détenues ?","o":["Oui","Non","Seulement leurs dividendes","Uniquement leur nombre d’employés"],"c":0,"e":"L’art. 29 al. 4 le prévoit expressément."},
{"a":"art. 30 LTVA","q":"Quel principe gouverne la correction en cas de double affectation ?","o":["Toujours un ratio de recettes","La proportion de l’utilisation","Toujours 50%","Le montant des dividendes"],"c":1,"e":"La correction doit refléter l’utilisation de l’input."},
{"a":"art. 30 LTVA","q":"Quelle démarche est la plus robuste pour les frais mixtes ?","o":["Affectation directe puis clé objective pour le résiduel","Tout mettre au prorata des dividendes","Déduire 100%","Choisir la clé maximisant le DIP"],"c":0,"e":"L’affectation directe puis une clé objective documentée est la démarche professionnelle."},
{"a":"art. 13 LTVA","q":"Condition centrale d’un groupe TVA :","o":["Même secteur d’activité","Direction unique","100% de participation obligatoire","Même fiduciaire"],"c":1,"e":"Les entités doivent être réunies sous une direction unique."},
{"a":"art. 15 OTVA","q":"La direction unique peut résulter :","o":["Uniquement de 100% du capital","De la majorité des voix, d’un contrat ou d’un autre moyen de contrôle","Seulement d’une fusion","Seulement d’un conseil d’administration identique"],"c":1,"e":"C’est la définition actuelle de l’art. 15 OTVA."},
{"a":"art. 17 OTVA","q":"Le cercle des membres du groupe TVA :","o":["Doit inclure toutes les sociétés du groupe mondial","Peut être choisi parmi les entités admissibles ; des sous-groupes sont possibles","Doit exclure les holdings","Est fixé par le canton"],"c":1,"e":"L’art. 17 permet de déterminer librement le cercle parmi les personnes admissibles."},
{"a":"art. 17a OTVA","q":"Qui peut représenter un groupe TVA ?","o":["Uniquement la société mère","Un membre établi en Suisse ou une personne non membre établie en Suisse","Uniquement une fiduciaire membre","N’importe quelle personne à l’étranger"],"c":1,"e":"Depuis 2025, l’art. 17a prévoit explicitement ces deux possibilités."},
{"a":"art. 18 OTVA","q":"La date d’effet d’une demande de groupe TVA dépend notamment :","o":["D’un délai fixe unique au 31 janvier","Du moment où les conditions sont remplies et de l’état des décomptes/délais","Du montant des dividendes","Du choix de la banque"],"c":1,"e":"L’art. 18 OTVA modernisé lie l’effet aux conditions et à la remise des décomptes/délais."},
{"a":"révision TVA","q":"L’obligation spécifique d’utiliser le portail en ligne pour les démarches d’imposition de groupe est annoncée pour :","o":["01.01.2025","01.01.2026","01.01.2027","Elle n’est jamais prévue"],"c":2,"e":"L’AFC indique l’entrée en vigueur au 1er janvier 2027 pour cette obligation spécifique."},
{"a":"art. 15 LTVA · art. 22 OTVA","q":"La responsabilité solidaire des membres couvre en principe :","o":["Impôt, intérêts et frais nés pendant l’appartenance","Uniquement les amendes","Uniquement la dette propre de chaque facture interne","Aucune dette"],"c":0,"e":"Les amendes sont exclues de la solidarité visée par l’art. 22 OTVA."},
{"a":"art. 22 OTVA","q":"Les amendes du groupe sont-elles comprises dans la responsabilité solidaire des membres ?","o":["Oui","Non"],"c":1,"e":"L’art. 22 OTVA les exclut."},
{"a":"art. 22 OTVA","q":"Une sortie du groupe permet-elle toujours d’échapper aux créances passées ?","o":["Oui","Non"],"c":1,"e":"Certaines situations, notamment contrôle annoncé ou notification d’estimation, empêchent de se soustraire à la solidarité par la sortie."},
{"a":"art. 13 LTVA","q":"Les prestations entre membres d’un même groupe TVA sont :","o":["Facturées avec 8,1%","Internes au sujet fiscal unique et non imposées comme opérations entre assujettis distincts","Toujours exonérées art. 23","Toujours soumises à acquisition tax"],"c":1,"e":"Le groupe est traité comme un seul sujet fiscal."},
{"a":"art. 38 LTVA","q":"Une cession de branche entre assujettis avec impôt théorique > CHF 10’000 peut-elle relever obligatoirement de la procédure de déclaration ?","o":["Oui, si les autres conditions art. 38 sont réunies","Jamais","Seulement si l’acheteur est étranger","Uniquement avec un ruling"],"c":0,"e":"Le seuil et la nature du transfert font partie du test de l’art. 38."},
{"a":"art. 38 LTVA","q":"Un transfert à une personne étroitement liée peut-il déclencher la procédure obligatoire même indépendamment du seuil CHF 10’000 ?","o":["Oui, si les autres conditions sont remplies","Non"],"c":0,"e":"Le lien étroit est un déclencheur alternatif prévu par l’art. 38 al. 1."},
{"a":"Formulaire 764","q":"Quel formulaire AFC documente la procédure de déclaration art. 38 ?","o":["764","1050","201","110"],"c":0,"e":"Le formulaire n° 764 est la référence actuelle."},
{"a":"AFC 17.11.2025","q":"Application obligatoire du formulaire 764 : signatures des deux parties depuis le 17.11.2025 ?","o":["Toujours requises","Non, elles ne sont plus nécessaires","Seulement signature du notaire","Seulement signature AFC"],"c":1,"e":"La révision du formulaire a supprimé les signatures dans le cas obligatoire."},
{"a":"AFC 17.11.2025","q":"Application facultative de la procédure de déclaration :","o":["Aucune signature","Signatures juridiquement contraignantes des deux parties restent nécessaires","Signature AFC uniquement","Signature du vendeur uniquement"],"c":1,"e":"L’AFC maintient les deux signatures pour la procédure facultative."},
{"a":"art. 38 al. 4 LTVA","q":"Dans la procédure de déclaration, l’acquéreur reprend pour les valeurs transférées :","o":["Uniquement le prix commercial","La base de calcul et le coefficient DIP de l’aliénateur","Aucune donnée historique","Uniquement la durée d’amortissement comptable"],"c":1,"e":"C’est la règle de l’art. 38 al. 4."},
{"a":"art. 45 LTVA","q":"Une facture étrangère est-elle automatiquement soumise à l’impôt sur les acquisitions ?","o":["Oui","Non, il faut vérifier catégorie, lieu, fournisseur et exclusions/exonérations"],"c":1,"e":"La qualification du flux précède l’auto-imposition."},
{"a":"art. 78 LTVA","q":"Le contrôle TVA doit en principe être clos dans les 360 jours par :","o":["Une notification d’estimation","Une amende","Un ruling","Une facture du contrôleur"],"c":0,"e":"L’AFC clôt le contrôle par une notification d’estimation."},
{"a":"art. 43 al. 1 let. b","q":"Une notification d’estimation peut entrer en force notamment par :","o":["Reconnaissance écrite ou paiement sans réserve","Simple lecture du courrier","Un appel téléphonique","Silence de 24 heures"],"c":0,"e":"L’AFC le rappelle expressément dans sa procédure de contrôle."},
{"a":"art. 82 LTVA","q":"Si l’assujetti n’est pas d’accord avec la notification d’estimation, il peut :","o":["Demander une décision à l’AFC","Attendre obligatoirement cinq ans","Saisir directement le Tribunal fédéral","Ignorer la notification"],"c":0,"e":"L’AFC indique la possibilité de demander une décision selon l’art. 82."},
{"a":"art. 83 LTVA","q":"Délai de réclamation contre une décision AFC en TVA :","o":["10 jours","30 jours","60 jours","1 an"],"c":1,"e":"La réclamation est formée dans les 30 jours."}
]
qjson=json.dumps(qs,ensure_ascii=False,separators=(',',':'))
sub(r'const QS=\[.*?\];\nconst QUIZ=', 'const QS='+qjson+';\nconst QUIZ=', 'QCM rebuild')

# ------------------------------------------------------------------
# Rebuild 30 flashcards
# ------------------------------------------------------------------
cards=[
{"cat":"Fondamentaux","t":"Participation qualifiée","d":"Participation visée à l’art. 29 ; une part de 10% au moins du capital est notamment considérée comme participation.","a":"art. 29 al. 2–3"},
{"cat":"Fondamentaux","t":"Activité entrepreneuriale de participation","d":"Acquisition, détention et aliénation de participations qualifiées constituent une activité entrepreneuriale.","a":"art. 10 al. 1ter"},
{"cat":"Fondamentaux","t":"Assujettissement volontaire","d":"Renonciation à la libération pour une activité entrepreneuriale lorsque les conditions sont remplies.","a":"art. 11"},
{"cat":"Fondamentaux","t":"Dividende","d":"Pas une contre-prestation ; pas de réduction du DIP du seul fait de sa réception.","a":"art. 18 al. 2 let. f · 33 al. 1"},
{"cat":"Fondamentaux","t":"Intérêt intragroupe","d":"Opération financière généralement exclue ; distinguer du dividende.","a":"art. 21 al. 2 ch. 19"},
{"cat":"Fondamentaux","t":"Management fee","d":"Vérifier prestation réelle, bénéficiaire, lieu et valeur ; documenter l’exécution.","a":"art. 18 · 24"},
{"cat":"DIP","t":"Art. 29 al. 2","d":"Régime spécifique du DIP pour acquisition, détention et aliénation de participations qualifiées et certaines restructurations.","a":"art. 29 al. 2"},
{"cat":"DIP","t":"Art. 29 al. 4","d":"Une société holding peut prendre en compte l’activité entrepreneuriale donnant droit au DIP des entreprises détenues.","a":"art. 29 al. 4"},
{"cat":"DIP","t":"Double affectation","d":"Correction du DIP en proportion de l’utilisation lorsqu’un input sert des activités donnant et ne donnant pas droit.","a":"art. 30"},
{"cat":"DIP","t":"Affectation directe","d":"Rattacher d’abord les coûts à leur activité avant toute clé globale.","a":"art. 28–30"},
{"cat":"DIP","t":"Clé objective","d":"Une clé de coûts mixtes doit refléter l’usage économique et être documentée ; les recettes ne sont pas une formule automatique.","a":"art. 30"},
{"cat":"DIP","t":"Dividendes et prorata","d":"Ne pas placer mécaniquement les dividendes au dénominateur : art. 33 al. 1 interdit une réduction du seul fait de leur réception.","a":"art. 33 al. 1"},
{"cat":"Management","t":"Personne étroitement liée","d":"La contre-prestation correspond à la valeur qui aurait été convenue entre tiers indépendants.","a":"art. 24 al. 2"},
{"cat":"Management","t":"Dossier de preuve","d":"Contrat, livrables, temps, coûts, méthode de prix et paiements selon les faits ; pas de checklist universelle.","a":"preuve / art. 24"},
{"cat":"Management","t":"Refacturation sans marge","d":"La marge zéro ne supprime pas l’existence d’une prestation ; qualifier le flux.","a":"art. 18 · 24"},
{"cat":"Groupe TVA","t":"Direction unique","d":"Contrôle du comportement par majorité des voix, contrat ou autre moyen.","a":"art. 15 OTVA"},
{"cat":"Groupe TVA","t":"Périmètre","d":"Choix libre parmi les entités admissibles ; sous-groupes possibles.","a":"art. 17 OTVA"},
{"cat":"Groupe TVA","t":"Représentant","d":"Membre établi en Suisse ou personne non membre ayant domicile/siège en Suisse.","a":"art. 17a OTVA"},
{"cat":"Groupe TVA","t":"Demande","d":"Date d’effet selon moment où les conditions sont remplies, décomptes remis et délais.","a":"art. 18 OTVA"},
{"cat":"Groupe TVA","t":"Flux internes","d":"Pas de TVA comme opérations entre assujettis distincts ; suivi interne nécessaire.","a":"art. 13 LTVA"},
{"cat":"Groupe TVA","t":"Responsabilité solidaire","d":"Impôt, intérêts et frais nés pendant l’appartenance ; amendes exclues.","a":"art. 15 LTVA · 22 OTVA"},
{"cat":"Groupe TVA","t":"Sortie et passé","d":"Une sortie ne purge pas toujours la solidarité, notamment si contrôle ou notification sont déjà intervenus.","a":"art. 22 OTVA"},
{"cat":"Restructurations","t":"Share deal","d":"Transfert de titres / participation ; coûts à analyser notamment sous art. 29.","a":"art. 29"},
{"cat":"Restructurations","t":"Asset deal","d":"Transfert d’actifs ; qualifier chaque élément et tester art. 38 si patrimoine / branche.","a":"art. 38"},
{"cat":"Restructurations","t":"Formulaire 764","d":"Formulaire AFC pour la procédure de déclaration, révisé le 17.11.2025.","a":"art. 38 · AFC"},
{"cat":"Restructurations","t":"Signatures 764","d":"Obligatoire : signatures non nécessaires ; facultatif : signatures juridiquement contraignantes des deux parties.","a":"AFC 17.11.2025"},
{"cat":"Restructurations","t":"Reprise chez l’acquéreur","d":"Base de calcul et coefficient applicable à la déduction du DIP pour les valeurs transférées.","a":"art. 38 al. 4"},
{"cat":"Contrôle","t":"Notification d’estimation","d":"Clôt le contrôle TVA et fixe la créance fiscale des périodes contrôlées.","a":"art. 78"},
{"cat":"Contrôle","t":"Paiement sans réserve","d":"Peut faire entrer en force la créance fixée par la notification d’estimation.","a":"art. 43 al. 1 let. b"},
{"cat":"Contrôle","t":"Décision et réclamation","d":"En désaccord avec la notification : demander décision art. 82 ; réclamation contre décision dans 30 jours selon art. 83.","a":"art. 82–83"}
]
cjson=json.dumps(cards,ensure_ascii=False,separators=(',',':'))
sub(r'const CARDS=\[.*?\];\nconst FC=', 'const CARDS='+cjson+';\nconst FC=', 'flashcards rebuild')

# ------------------------------------------------------------------
# JS completion / timer / current dashboard sync
# ------------------------------------------------------------------
rep('this.time=25*60','this.time=30*60','quiz timer js')
rep("const pct=Math.round(n/SECS.length*100);","const pct=state.completed?100:Math.round(n/SECS.length*100);",'completed progress',True)
old_finish="finish(){state.completed=1; PROG.save(); alert('✅ Module M07 Holdings terminé !\\n\\nVersion finale 10/10 validée.');}"
new_finish="""finish(){state.completed=1; PROG.save(); syncDashboardDone(); const box=document.getElementById('m07-complete'); if(box) box.style.display='flex'; PROG.update();}"""
rep(old_finish,new_finish,'finish handler',True)
completion_js='''
function syncDashboardDone(){
  try{
    const k='tvaSpecialisteTvaDashboardV1';
    const d=JSON.parse(localStorage.getItem(k)||'{}');
    d.M07='done';
    localStorage.setItem(k,JSON.stringify(d));
  }catch(e){}
}
function goNextModule(){PROG.finish();window.location.href='m08-immobilier-construction-tva.html';}
'''
rep('const CASES={',completion_js+'\nconst CASES={','completion functions',True)
rep("document.addEventListener('DOMContentLoaded',()=>{SECS.forEach(s=>{const el=document.getElementById('sec-'+s); if(el) el.style.display=s==='theory'?'block':'none';}); PROG.update();});",
    "document.addEventListener('DOMContentLoaded',()=>{SECS.forEach(s=>{const el=document.getElementById('sec-'+s); if(el) el.style.display=s==='theory'?'block':'none';}); if(state.completed){const box=document.getElementById('m07-complete');if(box)box.style.display='flex';syncDashboardDone();} PROG.update();});",'completion init',True)

# Preserve existing storage key to avoid wiping learner state, but remove visible legacy claims.
for old,new in [
('Dossier expert 10/10','Dossier professionnel'),
('final 10/10','audit professionnel'),
('Version finale 10/10','Version professionnelle'),
('Risque Noir AFC','Risque élevé'),
('Risque Noir','Risque élevé'),
('pratique AFC AFC','pratique AFC'),
('l\'pratique AFC','la pratique AFC'),
('lors d’un contrôle lors d\'un contrôle','lors d’un contrôle'),
('lors d\'un contrôle lors d\'un contrôle','lors d’un contrôle'),
]: rep(old,new,'cleanup '+old[:25])

# Never leave the previously misassigned case-law references in the learning material.
for bad in ['ATAF A-1558/2014','A-1558/2014','ATAF A-6362/2014','A-6362/2014','ATAF A-2454/2020','A-2454/2020','ATF 138 II 251']:
    rep(bad,'référence retirée après contrôle de pertinence','remove '+bad)

p.write_text(t,encoding='utf-8')
print('M07 changes',len(changes),'bytes',len(t.encode()))
for c in changes: print(' -',c)
